// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: security.proto

package contentsecurityservice

import (
	"context"

	"sea-try-go/service/security/rpc/pb/sea-try-go/service/security/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AlternativeDecision        = pb.AlternativeDecision
	ArtifactsReference         = pb.ArtifactsReference
	DecisionConstraints        = pb.DecisionConstraints
	DecisionRecord             = pb.DecisionRecord
	DetectImageAdBatchRequest  = pb.DetectImageAdBatchRequest
	DetectImageAdBatchResponse = pb.DetectImageAdBatchResponse
	DetectImageAdRequest       = pb.DetectImageAdRequest
	DetectImageAdResponse      = pb.DetectImageAdResponse
	DetectOptions              = pb.DetectOptions
	ExperimentInfo             = pb.ExperimentInfo
	ObservabilityContext       = pb.ObservabilityContext
	QualityValidation          = pb.QualityValidation
	SanitizeContentRequest     = pb.SanitizeContentRequest
	SanitizeContentResponse    = pb.SanitizeContentResponse
	SanitizeOptions            = pb.SanitizeOptions
	SingleImageRequest         = pb.SingleImageRequest
	SingleImageResponse        = pb.SingleImageResponse
	TokensUsage                = pb.TokensUsage

	ContentSecurityService interface {
		SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error)
	}

	defaultContentSecurityService struct {
		cli zrpc.Client
	}
)

func NewContentSecurityService(cli zrpc.Client) ContentSecurityService {
	return &defaultContentSecurityService{
		cli: cli,
	}
}

func (m *defaultContentSecurityService) SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error) {
	client := pb.NewContentSecurityServiceClient(m.cli.Conn())
	return client.SanitizeContent(ctx, in, opts...)
}
