// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	message "sea-try-go/service/message/api/internal/handler/message"
	messageadmin "sea-try-go/service/message/api/internal/handler/messageadmin"
	"sea-try-go/service/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/conversations/list",
				Handler: message.ListConversationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations/messages",
				Handler: message.GetConversationMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations/read",
				Handler: message.MarkConversationReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations/send",
				Handler: message.SendUserChatMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notifications/list",
				Handler: message.ListNotificationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notifications/read",
				Handler: message.MarkNotificationReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notifications/readall",
				Handler: message.MarkAllNotificationsReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/unread",
				Handler: message.GetUnreadSummaryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserAuth.AccessSecret),
		rest.WithPrefix("/message/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/conversations/list",
				Handler: messageadmin.ListAdminConversationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations/messages",
				Handler: messageadmin.GetAdminConversationMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations/read",
				Handler: messageadmin.MarkAdminConversationReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations/send",
				Handler: messageadmin.SendAdminChatMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notifications/send",
				Handler: messageadmin.SendAdminNotificationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
		rest.WithPrefix("/message/v1/admin"),
	)
}
