global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "etcd"
    metrics_path: /metrics
    static_configs:
      - targets: ["etcd:2379"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "minio-cluster"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: "minio-node"
    metrics_path: /minio/v2/metrics/node
    static_configs:
      - targets: ["minio:9000"]

  - job_name: "article-api"
    static_configs:
      - targets: ["host.docker.internal:9091"]

  - job_name: "article-rpc"
    static_configs:
      - targets: ["host.docker.internal:9092"]

  - job_name: "security-rpc"
    static_configs:
      - targets: ["host.docker.internal:9093"]

  - job_name: "user-rpc"
    static_configs:
      - targets: ["host.docker.internal:9094"]

  - job_name: "user-api"
    static_configs:
      - targets: ["host.docker.internal:9095"]

  - job_name: "admin-api"
    static_configs:
      - targets: ["host.docker.internal:9096"]

  - job_name: "admin-rpc"
    static_configs:
      - targets: ["host.docker.internal:9097"]

  - job_name: "message-api"
    static_configs:
      - targets: ["host.docker.internal:16066"]

  - job_name: "message-rpc"
    static_configs:
      - targets: ["host.docker.internal:16067"]
