// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/security.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 可观测性上下文 - 用于端到端链路追踪
type ObservabilityContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 贯穿整条链路的唯一追踪ID
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 当前步骤的Span ID
	SpanId string `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// 父Span ID（用于构建调用树）
	ParentSpanId string `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	// 业务请求ID
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 场景入口（低基数，便于聚合）
	Surface string `protobuf:"bytes,5,opt,name=surface,proto3" json:"surface,omitempty"`
	// 实验ID列表
	ExpIds        []*ExperimentInfo `protobuf:"bytes,6,rep,name=exp_ids,json=expIds,proto3" json:"exp_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservabilityContext) Reset() {
	*x = ObservabilityContext{}
	mi := &file_proto_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityContext) ProtoMessage() {}

func (x *ObservabilityContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityContext.ProtoReflect.Descriptor instead.
func (*ObservabilityContext) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{0}
}

func (x *ObservabilityContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ObservabilityContext) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ObservabilityContext) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *ObservabilityContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ObservabilityContext) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *ObservabilityContext) GetExpIds() []*ExperimentInfo {
	if x != nil {
		return x.ExpIds
	}
	return nil
}

// 实验信息
type ExperimentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Variant       string                 `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentInfo) Reset() {
	*x = ExperimentInfo{}
	mi := &file_proto_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentInfo) ProtoMessage() {}

func (x *ExperimentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentInfo.ProtoReflect.Descriptor instead.
func (*ExperimentInfo) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{1}
}

func (x *ExperimentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExperimentInfo) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

// 决策记录 - 记录AI/系统的决策过程
type DecisionRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 决策类型（枚举：route/retrieve/tool_select等）
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// 选择的动作/路径
	Chosen string `protobuf:"bytes,2,opt,name=chosen,proto3" json:"chosen,omitempty"`
	// 决策置信度（0.0-1.0）
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// 决策原因码（结构化，便于聚合告警）
	ReasonCodes []string `protobuf:"bytes,4,rep,name=reason_codes,json=reasonCodes,proto3" json:"reason_codes,omitempty"`
	// 信号摘要（严控基数）
	Signals map[string]string `protobuf:"bytes,5,rep,name=signals,proto3" json:"signals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 约束/门槛
	Constraints *DecisionConstraints `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	// 备选方案（最多2-3个）
	Alternatives []*AlternativeDecision `protobuf:"bytes,7,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	// 大对象引用（避免直接存储大字段）
	ArtifactsRef  *ArtifactsReference `protobuf:"bytes,8,opt,name=artifacts_ref,json=artifactsRef,proto3" json:"artifacts_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRecord) Reset() {
	*x = DecisionRecord{}
	mi := &file_proto_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRecord) ProtoMessage() {}

func (x *DecisionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRecord.ProtoReflect.Descriptor instead.
func (*DecisionRecord) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{2}
}

func (x *DecisionRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DecisionRecord) GetChosen() string {
	if x != nil {
		return x.Chosen
	}
	return ""
}

func (x *DecisionRecord) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DecisionRecord) GetReasonCodes() []string {
	if x != nil {
		return x.ReasonCodes
	}
	return nil
}

func (x *DecisionRecord) GetSignals() map[string]string {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *DecisionRecord) GetConstraints() *DecisionConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *DecisionRecord) GetAlternatives() []*AlternativeDecision {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *DecisionRecord) GetArtifactsRef() *ArtifactsReference {
	if x != nil {
		return x.ArtifactsRef
	}
	return nil
}

// 决策约束
type DecisionConstraints struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxLatencyMs    int32                  `protobuf:"varint,1,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	MaxToolCalls    int32                  `protobuf:"varint,2,opt,name=max_tool_calls,json=maxToolCalls,proto3" json:"max_tool_calls,omitempty"`
	MustCiteSources bool                   `protobuf:"varint,3,opt,name=must_cite_sources,json=mustCiteSources,proto3" json:"must_cite_sources,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecisionConstraints) Reset() {
	*x = DecisionConstraints{}
	mi := &file_proto_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionConstraints) ProtoMessage() {}

func (x *DecisionConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionConstraints.ProtoReflect.Descriptor instead.
func (*DecisionConstraints) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{3}
}

func (x *DecisionConstraints) GetMaxLatencyMs() int32 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *DecisionConstraints) GetMaxToolCalls() int32 {
	if x != nil {
		return x.MaxToolCalls
	}
	return 0
}

func (x *DecisionConstraints) GetMustCiteSources() bool {
	if x != nil {
		return x.MustCiteSources
	}
	return false
}

// 备选决策
type AlternativeDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	RejectCode    string                 `protobuf:"bytes,3,opt,name=reject_code,json=rejectCode,proto3" json:"reject_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlternativeDecision) Reset() {
	*x = AlternativeDecision{}
	mi := &file_proto_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlternativeDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlternativeDecision) ProtoMessage() {}

func (x *AlternativeDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlternativeDecision.ProtoReflect.Descriptor instead.
func (*AlternativeDecision) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{4}
}

func (x *AlternativeDecision) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AlternativeDecision) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AlternativeDecision) GetRejectCode() string {
	if x != nil {
		return x.RejectCode
	}
	return ""
}

// 大对象引用
type ArtifactsReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromptRef     string                 `protobuf:"bytes,1,opt,name=prompt_ref,json=promptRef,proto3" json:"prompt_ref,omitempty"`
	ToolIoRef     string                 `protobuf:"bytes,2,opt,name=tool_io_ref,json=toolIoRef,proto3" json:"tool_io_ref,omitempty"`
	RetrievalRef  string                 `protobuf:"bytes,3,opt,name=retrieval_ref,json=retrievalRef,proto3" json:"retrieval_ref,omitempty"`
	ResponseRef   string                 `protobuf:"bytes,4,opt,name=response_ref,json=responseRef,proto3" json:"response_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactsReference) Reset() {
	*x = ArtifactsReference{}
	mi := &file_proto_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactsReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsReference) ProtoMessage() {}

func (x *ArtifactsReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsReference.ProtoReflect.Descriptor instead.
func (*ArtifactsReference) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactsReference) GetPromptRef() string {
	if x != nil {
		return x.PromptRef
	}
	return ""
}

func (x *ArtifactsReference) GetToolIoRef() string {
	if x != nil {
		return x.ToolIoRef
	}
	return ""
}

func (x *ArtifactsReference) GetRetrievalRef() string {
	if x != nil {
		return x.RetrievalRef
	}
	return ""
}

func (x *ArtifactsReference) GetResponseRef() string {
	if x != nil {
		return x.ResponseRef
	}
	return ""
}

// 质量验证结果
type QualityValidation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema校验是否通过
	SchemaValid bool `protobuf:"varint,1,opt,name=schema_valid,json=schemaValid,proto3" json:"schema_valid,omitempty"`
	// 引用校验是否通过
	CitationValid bool `protobuf:"varint,2,opt,name=citation_valid,json=citationValid,proto3" json:"citation_valid,omitempty"`
	// 声明与检索一致性检查
	// PASS: 通过, FAIL_CLAIMED_BUT_EMPTY: 声称有依据但为空, FAIL_CITATION_MISSING: 缺少引用
	ClaimGroundingCheck string `protobuf:"bytes,3,opt,name=claim_grounding_check,json=claimGroundingCheck,proto3" json:"claim_grounding_check,omitempty"`
	// 违规项列表
	Violations    []string `protobuf:"bytes,4,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityValidation) Reset() {
	*x = QualityValidation{}
	mi := &file_proto_security_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityValidation) ProtoMessage() {}

func (x *QualityValidation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityValidation.ProtoReflect.Descriptor instead.
func (*QualityValidation) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{6}
}

func (x *QualityValidation) GetSchemaValid() bool {
	if x != nil {
		return x.SchemaValid
	}
	return false
}

func (x *QualityValidation) GetCitationValid() bool {
	if x != nil {
		return x.CitationValid
	}
	return false
}

func (x *QualityValidation) GetClaimGroundingCheck() string {
	if x != nil {
		return x.ClaimGroundingCheck
	}
	return ""
}

func (x *QualityValidation) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

type SanitizeContentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Text    string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Options *SanitizeOptions       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	// 可观测性上下文
	ObservabilityContext *ObservabilityContext `protobuf:"bytes,3,opt,name=observability_context,json=observabilityContext,proto3" json:"observability_context,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SanitizeContentRequest) Reset() {
	*x = SanitizeContentRequest{}
	mi := &file_proto_security_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeContentRequest) ProtoMessage() {}

func (x *SanitizeContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeContentRequest.ProtoReflect.Descriptor instead.
func (*SanitizeContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{7}
}

func (x *SanitizeContentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SanitizeContentRequest) GetOptions() *SanitizeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SanitizeContentRequest) GetObservabilityContext() *ObservabilityContext {
	if x != nil {
		return x.ObservabilityContext
	}
	return nil
}

type SanitizeOptions struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	EnableHtmlSanitization        bool                   `protobuf:"varint,1,opt,name=enable_html_sanitization,json=enableHtmlSanitization,proto3" json:"enable_html_sanitization,omitempty"`
	EnableAdDetection             bool                   `protobuf:"varint,2,opt,name=enable_ad_detection,json=enableAdDetection,proto3" json:"enable_ad_detection,omitempty"`
	EnableUnicodeNormalization    bool                   `protobuf:"varint,3,opt,name=enable_unicode_normalization,json=enableUnicodeNormalization,proto3" json:"enable_unicode_normalization,omitempty"`
	EnableWhitespaceNormalization bool                   `protobuf:"varint,4,opt,name=enable_whitespace_normalization,json=enableWhitespaceNormalization,proto3" json:"enable_whitespace_normalization,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SanitizeOptions) Reset() {
	*x = SanitizeOptions{}
	mi := &file_proto_security_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeOptions) ProtoMessage() {}

func (x *SanitizeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeOptions.ProtoReflect.Descriptor instead.
func (*SanitizeOptions) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{8}
}

func (x *SanitizeOptions) GetEnableHtmlSanitization() bool {
	if x != nil {
		return x.EnableHtmlSanitization
	}
	return false
}

func (x *SanitizeOptions) GetEnableAdDetection() bool {
	if x != nil {
		return x.EnableAdDetection
	}
	return false
}

func (x *SanitizeOptions) GetEnableUnicodeNormalization() bool {
	if x != nil {
		return x.EnableUnicodeNormalization
	}
	return false
}

func (x *SanitizeOptions) GetEnableWhitespaceNormalization() bool {
	if x != nil {
		return x.EnableWhitespaceNormalization
	}
	return false
}

type SanitizeContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SanitizedText string                 `protobuf:"bytes,1,opt,name=sanitized_text,json=sanitizedText,proto3" json:"sanitized_text,omitempty"`
	IsAd          bool                   `protobuf:"varint,2,opt,name=is_ad,json=isAd,proto3" json:"is_ad,omitempty"`
	AdConfidence  float32                `protobuf:"fixed32,3,opt,name=ad_confidence,json=adConfidence,proto3" json:"ad_confidence,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 可观测性上下文（用于响应链路追踪）
	ObservabilityContext *ObservabilityContext `protobuf:"bytes,6,opt,name=observability_context,json=observabilityContext,proto3" json:"observability_context,omitempty"`
	// 决策记录
	Decision *DecisionRecord `protobuf:"bytes,7,opt,name=decision,proto3" json:"decision,omitempty"`
	// 质量验证结果
	Quality *QualityValidation `protobuf:"bytes,8,opt,name=quality,proto3" json:"quality,omitempty"`
	// 步骤耗时（毫秒）
	LatencyMs int32 `protobuf:"varint,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Token使用量
	Tokens        *TokensUsage `protobuf:"bytes,10,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeContentResponse) Reset() {
	*x = SanitizeContentResponse{}
	mi := &file_proto_security_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeContentResponse) ProtoMessage() {}

func (x *SanitizeContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeContentResponse.ProtoReflect.Descriptor instead.
func (*SanitizeContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{9}
}

func (x *SanitizeContentResponse) GetSanitizedText() string {
	if x != nil {
		return x.SanitizedText
	}
	return ""
}

func (x *SanitizeContentResponse) GetIsAd() bool {
	if x != nil {
		return x.IsAd
	}
	return false
}

func (x *SanitizeContentResponse) GetAdConfidence() float32 {
	if x != nil {
		return x.AdConfidence
	}
	return 0
}

func (x *SanitizeContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SanitizeContentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SanitizeContentResponse) GetObservabilityContext() *ObservabilityContext {
	if x != nil {
		return x.ObservabilityContext
	}
	return nil
}

func (x *SanitizeContentResponse) GetDecision() *DecisionRecord {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *SanitizeContentResponse) GetQuality() *QualityValidation {
	if x != nil {
		return x.Quality
	}
	return nil
}

func (x *SanitizeContentResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *SanitizeContentResponse) GetTokens() *TokensUsage {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Token使用量
type TokensUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokensIn      int32                  `protobuf:"varint,1,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut     int32                  `protobuf:"varint,2,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokensUsage) Reset() {
	*x = TokensUsage{}
	mi := &file_proto_security_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensUsage) ProtoMessage() {}

func (x *TokensUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensUsage.ProtoReflect.Descriptor instead.
func (*TokensUsage) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{10}
}

func (x *TokensUsage) GetTokensIn() int32 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *TokensUsage) GetTokensOut() int32 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

type SingleImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ImageBase64   string                 `protobuf:"bytes,2,opt,name=image_base64,json=imageBase64,proto3" json:"image_base64,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleImageRequest) Reset() {
	*x = SingleImageRequest{}
	mi := &file_proto_security_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleImageRequest) ProtoMessage() {}

func (x *SingleImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleImageRequest.ProtoReflect.Descriptor instead.
func (*SingleImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{11}
}

func (x *SingleImageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SingleImageRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *SingleImageRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type DetectImageAdBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*SingleImageRequest  `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Options       *DetectOptions         `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	BatchId       string                 `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectImageAdBatchRequest) Reset() {
	*x = DetectImageAdBatchRequest{}
	mi := &file_proto_security_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectImageAdBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectImageAdBatchRequest) ProtoMessage() {}

func (x *DetectImageAdBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectImageAdBatchRequest.ProtoReflect.Descriptor instead.
func (*DetectImageAdBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{12}
}

func (x *DetectImageAdBatchRequest) GetImages() []*SingleImageRequest {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *DetectImageAdBatchRequest) GetOptions() *DetectOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *DetectImageAdBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type SingleImageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsAd             bool                   `protobuf:"varint,1,opt,name=is_ad,json=isAd,proto3" json:"is_ad,omitempty"`
	AdConfidence     float32                `protobuf:"fixed32,2,opt,name=ad_confidence,json=adConfidence,proto3" json:"ad_confidence,omitempty"`
	ExtractedText    string                 `protobuf:"bytes,3,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	Success          bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ImageId          string                 `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ProcessingTimeMs int32                  `protobuf:"varint,7,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	ImageSizeBytes   int32                  `protobuf:"varint,8,opt,name=image_size_bytes,json=imageSizeBytes,proto3" json:"image_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SingleImageResponse) Reset() {
	*x = SingleImageResponse{}
	mi := &file_proto_security_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleImageResponse) ProtoMessage() {}

func (x *SingleImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleImageResponse.ProtoReflect.Descriptor instead.
func (*SingleImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{13}
}

func (x *SingleImageResponse) GetIsAd() bool {
	if x != nil {
		return x.IsAd
	}
	return false
}

func (x *SingleImageResponse) GetAdConfidence() float32 {
	if x != nil {
		return x.AdConfidence
	}
	return 0
}

func (x *SingleImageResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *SingleImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SingleImageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SingleImageResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *SingleImageResponse) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *SingleImageResponse) GetImageSizeBytes() int32 {
	if x != nil {
		return x.ImageSizeBytes
	}
	return 0
}

type DetectOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnableAdDetection    bool                   `protobuf:"varint,1,opt,name=enable_ad_detection,json=enableAdDetection,proto3" json:"enable_ad_detection,omitempty"`
	ConfidenceThreshold  float32                `protobuf:"fixed32,2,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	EnableTextExtraction bool                   `protobuf:"varint,3,opt,name=enable_text_extraction,json=enableTextExtraction,proto3" json:"enable_text_extraction,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DetectOptions) Reset() {
	*x = DetectOptions{}
	mi := &file_proto_security_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectOptions) ProtoMessage() {}

func (x *DetectOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectOptions.ProtoReflect.Descriptor instead.
func (*DetectOptions) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{14}
}

func (x *DetectOptions) GetEnableAdDetection() bool {
	if x != nil {
		return x.EnableAdDetection
	}
	return false
}

func (x *DetectOptions) GetConfidenceThreshold() float32 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

func (x *DetectOptions) GetEnableTextExtraction() bool {
	if x != nil {
		return x.EnableTextExtraction
	}
	return false
}

type DetectImageAdBatchResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Results               []*SingleImageResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Success               bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	BatchId               string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TotalProcessingTimeMs int32                  `protobuf:"varint,5,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	SuccessfulCount       int32                  `protobuf:"varint,6,opt,name=successful_count,json=successfulCount,proto3" json:"successful_count,omitempty"`
	FailedCount           int32                  `protobuf:"varint,7,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	AdDetectionRate       float32                `protobuf:"fixed32,8,opt,name=ad_detection_rate,json=adDetectionRate,proto3" json:"ad_detection_rate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DetectImageAdBatchResponse) Reset() {
	*x = DetectImageAdBatchResponse{}
	mi := &file_proto_security_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectImageAdBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectImageAdBatchResponse) ProtoMessage() {}

func (x *DetectImageAdBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectImageAdBatchResponse.ProtoReflect.Descriptor instead.
func (*DetectImageAdBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{15}
}

func (x *DetectImageAdBatchResponse) GetResults() []*SingleImageResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DetectImageAdBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetectImageAdBatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DetectImageAdBatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *DetectImageAdBatchResponse) GetTotalProcessingTimeMs() int32 {
	if x != nil {
		return x.TotalProcessingTimeMs
	}
	return 0
}

func (x *DetectImageAdBatchResponse) GetSuccessfulCount() int32 {
	if x != nil {
		return x.SuccessfulCount
	}
	return 0
}

func (x *DetectImageAdBatchResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *DetectImageAdBatchResponse) GetAdDetectionRate() float32 {
	if x != nil {
		return x.AdDetectionRate
	}
	return 0
}

type DetectImageAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ImageBase64   string                 `protobuf:"bytes,2,opt,name=image_base64,json=imageBase64,proto3" json:"image_base64,omitempty"`
	Options       *DetectOptions         `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectImageAdRequest) Reset() {
	*x = DetectImageAdRequest{}
	mi := &file_proto_security_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectImageAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectImageAdRequest) ProtoMessage() {}

func (x *DetectImageAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectImageAdRequest.ProtoReflect.Descriptor instead.
func (*DetectImageAdRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{16}
}

func (x *DetectImageAdRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *DetectImageAdRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *DetectImageAdRequest) GetOptions() *DetectOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DetectImageAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAd          bool                   `protobuf:"varint,1,opt,name=is_ad,json=isAd,proto3" json:"is_ad,omitempty"`
	AdConfidence  float32                `protobuf:"fixed32,2,opt,name=ad_confidence,json=adConfidence,proto3" json:"ad_confidence,omitempty"`
	ExtractedText string                 `protobuf:"bytes,3,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectImageAdResponse) Reset() {
	*x = DetectImageAdResponse{}
	mi := &file_proto_security_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectImageAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectImageAdResponse) ProtoMessage() {}

func (x *DetectImageAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectImageAdResponse.ProtoReflect.Descriptor instead.
func (*DetectImageAdResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{17}
}

func (x *DetectImageAdResponse) GetIsAd() bool {
	if x != nil {
		return x.IsAd
	}
	return false
}

func (x *DetectImageAdResponse) GetAdConfidence() float32 {
	if x != nil {
		return x.AdConfidence
	}
	return 0
}

func (x *DetectImageAdResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *DetectImageAdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetectImageAdResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_security_proto protoreflect.FileDescriptor

const file_proto_security_proto_rawDesc = "" +
	"\n" +
	"\x14proto/security.proto\x12\bsecurity\"\xdc\x01\n" +
	"\x14ObservabilityContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x18\n" +
	"\asurface\x18\x05 \x01(\tR\asurface\x121\n" +
	"\aexp_ids\x18\x06 \x03(\v2\x18.security.ExperimentInfoR\x06expIds\">\n" +
	"\x0eExperimentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\avariant\x18\x02 \x01(\tR\avariant\"\xc3\x03\n" +
	"\x0eDecisionRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06chosen\x18\x02 \x01(\tR\x06chosen\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\freason_codes\x18\x04 \x03(\tR\vreasonCodes\x12?\n" +
	"\asignals\x18\x05 \x03(\v2%.security.DecisionRecord.SignalsEntryR\asignals\x12?\n" +
	"\vconstraints\x18\x06 \x01(\v2\x1d.security.DecisionConstraintsR\vconstraints\x12A\n" +
	"\falternatives\x18\a \x03(\v2\x1d.security.AlternativeDecisionR\falternatives\x12A\n" +
	"\rartifacts_ref\x18\b \x01(\v2\x1c.security.ArtifactsReferenceR\fartifactsRef\x1a:\n" +
	"\fSignalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x13DecisionConstraints\x12$\n" +
	"\x0emax_latency_ms\x18\x01 \x01(\x05R\fmaxLatencyMs\x12$\n" +
	"\x0emax_tool_calls\x18\x02 \x01(\x05R\fmaxToolCalls\x12*\n" +
	"\x11must_cite_sources\x18\x03 \x01(\bR\x0fmustCiteSources\"d\n" +
	"\x13AlternativeDecision\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x1f\n" +
	"\vreject_code\x18\x03 \x01(\tR\n" +
	"rejectCode\"\x9b\x01\n" +
	"\x12ArtifactsReference\x12\x1d\n" +
	"\n" +
	"prompt_ref\x18\x01 \x01(\tR\tpromptRef\x12\x1e\n" +
	"\vtool_io_ref\x18\x02 \x01(\tR\ttoolIoRef\x12#\n" +
	"\rretrieval_ref\x18\x03 \x01(\tR\fretrievalRef\x12!\n" +
	"\fresponse_ref\x18\x04 \x01(\tR\vresponseRef\"\xb1\x01\n" +
	"\x11QualityValidation\x12!\n" +
	"\fschema_valid\x18\x01 \x01(\bR\vschemaValid\x12%\n" +
	"\x0ecitation_valid\x18\x02 \x01(\bR\rcitationValid\x122\n" +
	"\x15claim_grounding_check\x18\x03 \x01(\tR\x13claimGroundingCheck\x12\x1e\n" +
	"\n" +
	"violations\x18\x04 \x03(\tR\n" +
	"violations\"\xb6\x01\n" +
	"\x16SanitizeContentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x123\n" +
	"\aoptions\x18\x02 \x01(\v2\x19.security.SanitizeOptionsR\aoptions\x12S\n" +
	"\x15observability_context\x18\x03 \x01(\v2\x1e.security.ObservabilityContextR\x14observabilityContext\"\x85\x02\n" +
	"\x0fSanitizeOptions\x128\n" +
	"\x18enable_html_sanitization\x18\x01 \x01(\bR\x16enableHtmlSanitization\x12.\n" +
	"\x13enable_ad_detection\x18\x02 \x01(\bR\x11enableAdDetection\x12@\n" +
	"\x1cenable_unicode_normalization\x18\x03 \x01(\bR\x1aenableUnicodeNormalization\x12F\n" +
	"\x1fenable_whitespace_normalization\x18\x04 \x01(\bR\x1denableWhitespaceNormalization\"\xc9\x03\n" +
	"\x17SanitizeContentResponse\x12%\n" +
	"\x0esanitized_text\x18\x01 \x01(\tR\rsanitizedText\x12\x13\n" +
	"\x05is_ad\x18\x02 \x01(\bR\x04isAd\x12#\n" +
	"\rad_confidence\x18\x03 \x01(\x02R\fadConfidence\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12S\n" +
	"\x15observability_context\x18\x06 \x01(\v2\x1e.security.ObservabilityContextR\x14observabilityContext\x124\n" +
	"\bdecision\x18\a \x01(\v2\x18.security.DecisionRecordR\bdecision\x125\n" +
	"\aquality\x18\b \x01(\v2\x1b.security.QualityValidationR\aquality\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x05R\tlatencyMs\x12-\n" +
	"\x06tokens\x18\n" +
	" \x01(\v2\x15.security.TokensUsageR\x06tokens\"I\n" +
	"\vTokensUsage\x12\x1b\n" +
	"\ttokens_in\x18\x01 \x01(\x05R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\x02 \x01(\x05R\ttokensOut\"n\n" +
	"\x12SingleImageRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12!\n" +
	"\fimage_base64\x18\x02 \x01(\tR\vimageBase64\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"\x9f\x01\n" +
	"\x19DetectImageAdBatchRequest\x124\n" +
	"\x06images\x18\x01 \x03(\v2\x1c.security.SingleImageRequestR\x06images\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.security.DetectOptionsR\aoptions\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\tR\abatchId\"\xa8\x02\n" +
	"\x13SingleImageResponse\x12\x13\n" +
	"\x05is_ad\x18\x01 \x01(\bR\x04isAd\x12#\n" +
	"\rad_confidence\x18\x02 \x01(\x02R\fadConfidence\x12%\n" +
	"\x0eextracted_text\x18\x03 \x01(\tR\rextractedText\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bimage_id\x18\x06 \x01(\tR\aimageId\x12,\n" +
	"\x12processing_time_ms\x18\a \x01(\x05R\x10processingTimeMs\x12(\n" +
	"\x10image_size_bytes\x18\b \x01(\x05R\x0eimageSizeBytes\"\xa8\x01\n" +
	"\rDetectOptions\x12.\n" +
	"\x13enable_ad_detection\x18\x01 \x01(\bR\x11enableAdDetection\x121\n" +
	"\x14confidence_threshold\x18\x02 \x01(\x02R\x13confidenceThreshold\x124\n" +
	"\x16enable_text_extraction\x18\x03 \x01(\bR\x14enableTextExtraction\"\xe2\x02\n" +
	"\x1aDetectImageAdBatchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.security.SingleImageResponseR\aresults\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId\x127\n" +
	"\x18total_processing_time_ms\x18\x05 \x01(\x05R\x15totalProcessingTimeMs\x12)\n" +
	"\x10successful_count\x18\x06 \x01(\x05R\x0fsuccessfulCount\x12!\n" +
	"\ffailed_count\x18\a \x01(\x05R\vfailedCount\x12*\n" +
	"\x11ad_detection_rate\x18\b \x01(\x02R\x0fadDetectionRate\"\x89\x01\n" +
	"\x14DetectImageAdRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12!\n" +
	"\fimage_base64\x18\x02 \x01(\tR\vimageBase64\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.security.DetectOptionsR\aoptions\"\xb7\x01\n" +
	"\x15DetectImageAdResponse\x12\x13\n" +
	"\x05is_ad\x18\x01 \x01(\bR\x04isAd\x12#\n" +
	"\rad_confidence\x18\x02 \x01(\x02R\fadConfidence\x12%\n" +
	"\x0eextracted_text\x18\x03 \x01(\tR\rextractedText\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage2p\n" +
	"\x16ContentSecurityService\x12V\n" +
	"\x0fSanitizeContent\x12 .security.SanitizeContentRequest\x1a!.security.SanitizeContentResponse2\xc9\x01\n" +
	"\x14ImageSecurityService\x12P\n" +
	"\rDetectImageAd\x12\x1e.security.DetectImageAdRequest\x1a\x1f.security.DetectImageAdResponse\x12_\n" +
	"\x12DetectImageAdBatch\x12#.security.DetectImageAdBatchRequest\x1a$.security.DetectImageAdBatchResponseB$Z\"sea-try-go/service/security/rpc/pbb\x06proto3"

var (
	file_proto_security_proto_rawDescOnce sync.Once
	file_proto_security_proto_rawDescData []byte
)

func file_proto_security_proto_rawDescGZIP() []byte {
	file_proto_security_proto_rawDescOnce.Do(func() {
		file_proto_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_security_proto_rawDesc), len(file_proto_security_proto_rawDesc)))
	})
	return file_proto_security_proto_rawDescData
}

var file_proto_security_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_security_proto_goTypes = []any{
	(*ObservabilityContext)(nil),       // 0: security.ObservabilityContext
	(*ExperimentInfo)(nil),             // 1: security.ExperimentInfo
	(*DecisionRecord)(nil),             // 2: security.DecisionRecord
	(*DecisionConstraints)(nil),        // 3: security.DecisionConstraints
	(*AlternativeDecision)(nil),        // 4: security.AlternativeDecision
	(*ArtifactsReference)(nil),         // 5: security.ArtifactsReference
	(*QualityValidation)(nil),          // 6: security.QualityValidation
	(*SanitizeContentRequest)(nil),     // 7: security.SanitizeContentRequest
	(*SanitizeOptions)(nil),            // 8: security.SanitizeOptions
	(*SanitizeContentResponse)(nil),    // 9: security.SanitizeContentResponse
	(*TokensUsage)(nil),                // 10: security.TokensUsage
	(*SingleImageRequest)(nil),         // 11: security.SingleImageRequest
	(*DetectImageAdBatchRequest)(nil),  // 12: security.DetectImageAdBatchRequest
	(*SingleImageResponse)(nil),        // 13: security.SingleImageResponse
	(*DetectOptions)(nil),              // 14: security.DetectOptions
	(*DetectImageAdBatchResponse)(nil), // 15: security.DetectImageAdBatchResponse
	(*DetectImageAdRequest)(nil),       // 16: security.DetectImageAdRequest
	(*DetectImageAdResponse)(nil),      // 17: security.DetectImageAdResponse
	nil,                                // 18: security.DecisionRecord.SignalsEntry
}
var file_proto_security_proto_depIdxs = []int32{
	1,  // 0: security.ObservabilityContext.exp_ids:type_name -> security.ExperimentInfo
	18, // 1: security.DecisionRecord.signals:type_name -> security.DecisionRecord.SignalsEntry
	3,  // 2: security.DecisionRecord.constraints:type_name -> security.DecisionConstraints
	4,  // 3: security.DecisionRecord.alternatives:type_name -> security.AlternativeDecision
	5,  // 4: security.DecisionRecord.artifacts_ref:type_name -> security.ArtifactsReference
	8,  // 5: security.SanitizeContentRequest.options:type_name -> security.SanitizeOptions
	0,  // 6: security.SanitizeContentRequest.observability_context:type_name -> security.ObservabilityContext
	0,  // 7: security.SanitizeContentResponse.observability_context:type_name -> security.ObservabilityContext
	2,  // 8: security.SanitizeContentResponse.decision:type_name -> security.DecisionRecord
	6,  // 9: security.SanitizeContentResponse.quality:type_name -> security.QualityValidation
	10, // 10: security.SanitizeContentResponse.tokens:type_name -> security.TokensUsage
	11, // 11: security.DetectImageAdBatchRequest.images:type_name -> security.SingleImageRequest
	14, // 12: security.DetectImageAdBatchRequest.options:type_name -> security.DetectOptions
	13, // 13: security.DetectImageAdBatchResponse.results:type_name -> security.SingleImageResponse
	14, // 14: security.DetectImageAdRequest.options:type_name -> security.DetectOptions
	7,  // 15: security.ContentSecurityService.SanitizeContent:input_type -> security.SanitizeContentRequest
	16, // 16: security.ImageSecurityService.DetectImageAd:input_type -> security.DetectImageAdRequest
	12, // 17: security.ImageSecurityService.DetectImageAdBatch:input_type -> security.DetectImageAdBatchRequest
	9,  // 18: security.ContentSecurityService.SanitizeContent:output_type -> security.SanitizeContentResponse
	17, // 19: security.ImageSecurityService.DetectImageAd:output_type -> security.DetectImageAdResponse
	15, // 20: security.ImageSecurityService.DetectImageAdBatch:output_type -> security.DetectImageAdBatchResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_security_proto_init() }
func file_proto_security_proto_init() {
	if File_proto_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_security_proto_rawDesc), len(file_proto_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_security_proto_goTypes,
		DependencyIndexes: file_proto_security_proto_depIdxs,
		MessageInfos:      file_proto_security_proto_msgTypes,
	}.Build()
	File_proto_security_proto = out.File
	file_proto_security_proto_goTypes = nil
	file_proto_security_proto_depIdxs = nil
}
