// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/security.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentSecurityService_SanitizeContent_FullMethodName = "/security.ContentSecurityService/SanitizeContent"
)

// ContentSecurityServiceClient is the client API for ContentSecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentSecurityServiceClient interface {
	SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error)
}

type contentSecurityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentSecurityServiceClient(cc grpc.ClientConnInterface) ContentSecurityServiceClient {
	return &contentSecurityServiceClient{cc}
}

func (c *contentSecurityServiceClient) SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SanitizeContentResponse)
	err := c.cc.Invoke(ctx, ContentSecurityService_SanitizeContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentSecurityServiceServer is the server API for ContentSecurityService service.
// All implementations must embed UnimplementedContentSecurityServiceServer
// for forward compatibility.
type ContentSecurityServiceServer interface {
	SanitizeContent(context.Context, *SanitizeContentRequest) (*SanitizeContentResponse, error)
	mustEmbedUnimplementedContentSecurityServiceServer()
}

// UnimplementedContentSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentSecurityServiceServer struct{}

func (UnimplementedContentSecurityServiceServer) SanitizeContent(context.Context, *SanitizeContentRequest) (*SanitizeContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SanitizeContent not implemented")
}
func (UnimplementedContentSecurityServiceServer) mustEmbedUnimplementedContentSecurityServiceServer() {
}
func (UnimplementedContentSecurityServiceServer) testEmbeddedByValue() {}

// UnsafeContentSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentSecurityServiceServer will
// result in compilation errors.
type UnsafeContentSecurityServiceServer interface {
	mustEmbedUnimplementedContentSecurityServiceServer()
}

func RegisterContentSecurityServiceServer(s grpc.ServiceRegistrar, srv ContentSecurityServiceServer) {
	// If the following call panics, it indicates UnimplementedContentSecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentSecurityService_ServiceDesc, srv)
}

func _ContentSecurityService_SanitizeContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SanitizeContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentSecurityServiceServer).SanitizeContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentSecurityService_SanitizeContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentSecurityServiceServer).SanitizeContent(ctx, req.(*SanitizeContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentSecurityService_ServiceDesc is the grpc.ServiceDesc for ContentSecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentSecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "security.ContentSecurityService",
	HandlerType: (*ContentSecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SanitizeContent",
			Handler:    _ContentSecurityService_SanitizeContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/security.proto",
}

const (
	ImageSecurityService_DetectImageAd_FullMethodName      = "/security.ImageSecurityService/DetectImageAd"
	ImageSecurityService_DetectImageAdBatch_FullMethodName = "/security.ImageSecurityService/DetectImageAdBatch"
)

// ImageSecurityServiceClient is the client API for ImageSecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageSecurityServiceClient interface {
	DetectImageAd(ctx context.Context, in *DetectImageAdRequest, opts ...grpc.CallOption) (*DetectImageAdResponse, error)
	DetectImageAdBatch(ctx context.Context, in *DetectImageAdBatchRequest, opts ...grpc.CallOption) (*DetectImageAdBatchResponse, error)
}

type imageSecurityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageSecurityServiceClient(cc grpc.ClientConnInterface) ImageSecurityServiceClient {
	return &imageSecurityServiceClient{cc}
}

func (c *imageSecurityServiceClient) DetectImageAd(ctx context.Context, in *DetectImageAdRequest, opts ...grpc.CallOption) (*DetectImageAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectImageAdResponse)
	err := c.cc.Invoke(ctx, ImageSecurityService_DetectImageAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageSecurityServiceClient) DetectImageAdBatch(ctx context.Context, in *DetectImageAdBatchRequest, opts ...grpc.CallOption) (*DetectImageAdBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectImageAdBatchResponse)
	err := c.cc.Invoke(ctx, ImageSecurityService_DetectImageAdBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageSecurityServiceServer is the server API for ImageSecurityService service.
// All implementations must embed UnimplementedImageSecurityServiceServer
// for forward compatibility.
type ImageSecurityServiceServer interface {
	DetectImageAd(context.Context, *DetectImageAdRequest) (*DetectImageAdResponse, error)
	DetectImageAdBatch(context.Context, *DetectImageAdBatchRequest) (*DetectImageAdBatchResponse, error)
	mustEmbedUnimplementedImageSecurityServiceServer()
}

// UnimplementedImageSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageSecurityServiceServer struct{}

func (UnimplementedImageSecurityServiceServer) DetectImageAd(context.Context, *DetectImageAdRequest) (*DetectImageAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectImageAd not implemented")
}
func (UnimplementedImageSecurityServiceServer) DetectImageAdBatch(context.Context, *DetectImageAdBatchRequest) (*DetectImageAdBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectImageAdBatch not implemented")
}
func (UnimplementedImageSecurityServiceServer) mustEmbedUnimplementedImageSecurityServiceServer() {}
func (UnimplementedImageSecurityServiceServer) testEmbeddedByValue()                              {}

// UnsafeImageSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageSecurityServiceServer will
// result in compilation errors.
type UnsafeImageSecurityServiceServer interface {
	mustEmbedUnimplementedImageSecurityServiceServer()
}

func RegisterImageSecurityServiceServer(s grpc.ServiceRegistrar, srv ImageSecurityServiceServer) {
	// If the following call panics, it indicates UnimplementedImageSecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageSecurityService_ServiceDesc, srv)
}

func _ImageSecurityService_DetectImageAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectImageAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSecurityServiceServer).DetectImageAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageSecurityService_DetectImageAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSecurityServiceServer).DetectImageAd(ctx, req.(*DetectImageAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageSecurityService_DetectImageAdBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectImageAdBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSecurityServiceServer).DetectImageAdBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageSecurityService_DetectImageAdBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSecurityServiceServer).DetectImageAdBatch(ctx, req.(*DetectImageAdBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageSecurityService_ServiceDesc is the grpc.ServiceDesc for ImageSecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageSecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "security.ImageSecurityService",
	HandlerType: (*ImageSecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectImageAd",
			Handler:    _ImageSecurityService_DetectImageAd_Handler,
		},
		{
			MethodName: "DetectImageAdBatch",
			Handler:    _ImageSecurityService_DetectImageAdBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/security.proto",
}
