// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: article.proto

package server

import (
	"context"

	"sea-try-go/service/article/rpc/internal/logic"
	"sea-try-go/service/article/rpc/internal/svc"
	"sea-try-go/service/article/rpc/pb"
)

type ArticleServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedArticleServiceServer
}

func NewArticleServiceServer(svcCtx *svc.ServiceContext) *ArticleServiceServer {
	return &ArticleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServiceServer) CreateArticle(ctx context.Context, in *__.CreateArticleRequest) (*__.CreateArticleResponse, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *ArticleServiceServer) GetArticle(ctx context.Context, in *__.GetArticleRequest) (*__.GetArticleResponse, error) {
	l := logic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

func (s *ArticleServiceServer) UpdateArticle(ctx context.Context, in *__.UpdateArticleRequest) (*__.UpdateArticleResponse, error) {
	l := logic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *ArticleServiceServer) DeleteArticle(ctx context.Context, in *__.DeleteArticleRequest) (*__.DeleteArticleResponse, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}

func (s *ArticleServiceServer) ListArticles(ctx context.Context, in *__.ListArticlesRequest) (*__.ListArticlesResponse, error) {
	l := logic.NewListArticlesLogic(ctx, s.svcCtx)
	return l.ListArticles(in)
}

func (s *ArticleServiceServer) UploadFile(ctx context.Context, in *__.UploadFileRequest) (*__.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *ArticleServiceServer) GetPresignedUploadUrl(ctx context.Context, in *__.GetPresignedUploadUrlRequest) (*__.GetPresignedUploadUrlResponse, error) {
	l := logic.NewGetPresignedUploadUrlLogic(ctx, s.svcCtx)
	return l.GetPresignedUploadUrl(in)
}
