// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: security.proto

package server

import (
	"context"

	contentsecurityservicelogic "sea-try-go/service/security/rpc/internal/logic/contentsecurityservice"
	"sea-try-go/service/security/rpc/internal/svc"
	"sea-try-go/service/security/rpc/pb/sea-try-go/service/security/rpc/pb"
)

type ContentSecurityServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedContentSecurityServiceServer
}

func NewContentSecurityServiceServer(svcCtx *svc.ServiceContext) *ContentSecurityServiceServer {
	return &ContentSecurityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentSecurityServiceServer) SanitizeContent(ctx context.Context, in *pb.SanitizeContentRequest) (*pb.SanitizeContentResponse, error) {
	l := contentsecurityservicelogic.NewSanitizeContentLogic(ctx, s.svcCtx)
	return l.SanitizeContent(in)
}