// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package messageservice

import (
	"context"

	"sea-try-go/service/message/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp                    = pb.BaseResp
	ChatMessageItem             = pb.ChatMessageItem
	ConversationItem            = pb.ConversationItem
	ConversationListReq         = pb.ConversationListReq
	ConversationListResp        = pb.ConversationListResp
	ConversationMessageListReq  = pb.ConversationMessageListReq
	ConversationMessageListResp = pb.ConversationMessageListResp
	MarkAllNotificationsReq     = pb.MarkAllNotificationsReq
	MarkConversationReadReq     = pb.MarkConversationReadReq
	MarkNotificationReq         = pb.MarkNotificationReq
	NotificationItem            = pb.NotificationItem
	NotificationListReq         = pb.NotificationListReq
	NotificationListResp        = pb.NotificationListResp
	SendChatMessageReq          = pb.SendChatMessageReq
	SendChatMessageResp         = pb.SendChatMessageResp
	SendNotificationReq         = pb.SendNotificationReq
	SendNotificationResp        = pb.SendNotificationResp
	UnreadSummaryReq            = pb.UnreadSummaryReq
	UnreadSummaryResp           = pb.UnreadSummaryResp

	MessageService interface {
		SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error)
		ListNotifications(ctx context.Context, in *NotificationListReq, opts ...grpc.CallOption) (*NotificationListResp, error)
		MarkNotificationRead(ctx context.Context, in *MarkNotificationReq, opts ...grpc.CallOption) (*BaseResp, error)
		MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReq, opts ...grpc.CallOption) (*BaseResp, error)
		GetUnreadSummary(ctx context.Context, in *UnreadSummaryReq, opts ...grpc.CallOption) (*UnreadSummaryResp, error)
		ListConversations(ctx context.Context, in *ConversationListReq, opts ...grpc.CallOption) (*ConversationListResp, error)
		GetConversationMessages(ctx context.Context, in *ConversationMessageListReq, opts ...grpc.CallOption) (*ConversationMessageListResp, error)
		SendChatMessage(ctx context.Context, in *SendChatMessageReq, opts ...grpc.CallOption) (*SendChatMessageResp, error)
		MarkConversationRead(ctx context.Context, in *MarkConversationReadReq, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

func (m *defaultMessageService) SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SendNotification(ctx, in, opts...)
}

func (m *defaultMessageService) ListNotifications(ctx context.Context, in *NotificationListReq, opts ...grpc.CallOption) (*NotificationListResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

func (m *defaultMessageService) MarkNotificationRead(ctx context.Context, in *MarkNotificationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.MarkNotificationRead(ctx, in, opts...)
}

func (m *defaultMessageService) MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.MarkAllNotificationsRead(ctx, in, opts...)
}

func (m *defaultMessageService) GetUnreadSummary(ctx context.Context, in *UnreadSummaryReq, opts ...grpc.CallOption) (*UnreadSummaryResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetUnreadSummary(ctx, in, opts...)
}

func (m *defaultMessageService) ListConversations(ctx context.Context, in *ConversationListReq, opts ...grpc.CallOption) (*ConversationListResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ListConversations(ctx, in, opts...)
}

func (m *defaultMessageService) GetConversationMessages(ctx context.Context, in *ConversationMessageListReq, opts ...grpc.CallOption) (*ConversationMessageListResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetConversationMessages(ctx, in, opts...)
}

func (m *defaultMessageService) SendChatMessage(ctx context.Context, in *SendChatMessageReq, opts ...grpc.CallOption) (*SendChatMessageResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SendChatMessage(ctx, in, opts...)
}

func (m *defaultMessageService) MarkConversationRead(ctx context.Context, in *MarkConversationReadReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.MarkConversationRead(ctx, in, opts...)
}
