// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: security.proto

package imagesecurityservice

import (
	"context"

	"sea-try-go/service/security/rpc/pb/sea-try-go/service/security/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AlternativeDecision        = pb.AlternativeDecision
	ArtifactsReference         = pb.ArtifactsReference
	DecisionConstraints        = pb.DecisionConstraints
	DecisionRecord             = pb.DecisionRecord
	DetectImageAdBatchRequest  = pb.DetectImageAdBatchRequest
	DetectImageAdBatchResponse = pb.DetectImageAdBatchResponse
	DetectImageAdRequest       = pb.DetectImageAdRequest
	DetectImageAdResponse      = pb.DetectImageAdResponse
	DetectOptions              = pb.DetectOptions
	ExperimentInfo             = pb.ExperimentInfo
	ObservabilityContext       = pb.ObservabilityContext
	QualityValidation          = pb.QualityValidation
	SanitizeContentRequest     = pb.SanitizeContentRequest
	SanitizeContentResponse    = pb.SanitizeContentResponse
	SanitizeOptions            = pb.SanitizeOptions
	SingleImageRequest         = pb.SingleImageRequest
	SingleImageResponse        = pb.SingleImageResponse
	TokensUsage                = pb.TokensUsage

	ImageSecurityService interface {
		DetectImageAd(ctx context.Context, in *DetectImageAdRequest, opts ...grpc.CallOption) (*DetectImageAdResponse, error)
		DetectImageAdBatch(ctx context.Context, in *DetectImageAdBatchRequest, opts ...grpc.CallOption) (*DetectImageAdBatchResponse, error)
	}

	defaultImageSecurityService struct {
		cli zrpc.Client
	}
)

func NewImageSecurityService(cli zrpc.Client) ImageSecurityService {
	return &defaultImageSecurityService{
		cli: cli,
	}
}

func (m *defaultImageSecurityService) DetectImageAd(ctx context.Context, in *DetectImageAdRequest, opts ...grpc.CallOption) (*DetectImageAdResponse, error) {
	client := pb.NewImageSecurityServiceClient(m.cli.Conn())
	return client.DetectImageAd(ctx, in, opts...)
}

func (m *defaultImageSecurityService) DetectImageAdBatch(ctx context.Context, in *DetectImageAdBatchRequest, opts ...grpc.CallOption) (*DetectImageAdBatchResponse, error) {
	client := pb.NewImageSecurityServiceClient(m.cli.Conn())
	return client.DetectImageAdBatch(ctx, in, opts...)
}
