// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	article "sea-try-go/service/article/api/internal/handler/article"
	"sea-try-go/service/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/article",
					Handler: article.CreateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/article/:id",
					Handler: article.UpdateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/article/:id",
					Handler: article.DeleteArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/article/upload/url",
					Handler: article.GetPresignedUploadUrlHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(70000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/article/:id",
					Handler: article.GetArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/articles",
					Handler: article.ListArticlesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: article.UploadImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(70000*time.Millisecond),
	)
}
