// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminSendChatReq struct {
	RecipientId    int64  `json:"recipient_id,string"`
	ConversationId int64  `json:"conversation_id,string,optional"`
	Content        string `json:"content"`
}

type AdminSendNotificationReq struct {
	Broadcast bool              `json:"broadcast,optional"`
	TargetId  int64             `json:"target_id,string,optional"`
	Kind      int32             `json:"kind,optional"`
	Title     string            `json:"title"`
	Content   string            `json:"content"`
	Extra     map[string]string `json:"extra,optional"`
}

type AdminSendNotificationResp struct {
	Affected int64 `json:"affected"`
}

type ChatMessageItem struct {
	Id             int64  `json:"id,string"`
	ConversationId int64  `json:"conversation_id,string"`
	SenderId       int64  `json:"sender_id,string"`
	SenderRole     int32  `json:"sender_role"`
	RecipientId    int64  `json:"recipient_id,string"`
	RecipientRole  int32  `json:"recipient_role"`
	Content        string `json:"content"`
	IsRead         bool   `json:"is_read"`
	CreatedAt      int64  `json:"created_at"`
}

type ConversationItem struct {
	ConversationId  int64  `json:"conversation_id,string"`
	PeerId          int64  `json:"peer_id,string"`
	PeerRole        int32  `json:"peer_role"`
	PeerName        string `json:"peer_name"`
	PeerEmail       string `json:"peer_email"`
	Status          int32  `json:"status"`
	UnreadCount     int64  `json:"unread_count"`
	LatestMessage   string `json:"latest_message"`
	LatestMessageAt int64  `json:"latest_message_at"`
	UpdatedAt       int64  `json:"updated_at"`
	CanSend         bool   `json:"can_send"`
}

type ConversationListResp struct {
	Items       []ConversationItem `json:"items"`
	Total       int64              `json:"total"`
	UnreadCount int64              `json:"unread_count"`
}

type ConversationMessagesReq struct {
	ConversationId int64 `json:"conversation_id,string"`
	Offset         int32 `json:"offset,optional"`
	Limit          int32 `json:"limit,optional"`
}

type ConversationMessagesResp struct {
	Items             []ChatMessageItem `json:"items"`
	Status            int32             `json:"status"`
	CanSend           bool              `json:"can_send"`
	PendingSenderId   int64             `json:"pending_sender_id,string"`
	PendingSenderRole int32             `json:"pending_sender_role"`
}

type EmptyReq struct {
}

type MarkConversationReadReq struct {
	ConversationId int64 `json:"conversation_id,string"`
}

type MarkNotificationReq struct {
	NotificationId int64 `json:"notification_id,string"`
}

type NotificationItem struct {
	Id          int64             `json:"id,string"`
	RecipientId int64             `json:"recipient_id,string"`
	SenderId    int64             `json:"sender_id,string"`
	SenderRole  int32             `json:"sender_role"`
	Kind        int32             `json:"kind"`
	Title       string            `json:"title"`
	Content     string            `json:"content"`
	IsRead      bool              `json:"is_read"`
	CreatedAt   int64             `json:"created_at"`
	Extra       map[string]string `json:"extra"`
}

type NotificationListResp struct {
	Items       []NotificationItem `json:"items"`
	Total       int64              `json:"total"`
	UnreadCount int64              `json:"unread_count"`
}

type PageReq struct {
	Offset     int32 `json:"offset,optional"`
	Limit      int32 `json:"limit,optional"`
	UnreadOnly bool  `json:"unread_only,optional"`
}

type SendChatResp struct {
	ConversationId int64           `json:"conversation_id,string"`
	Message        ChatMessageItem `json:"message"`
	Status         int32           `json:"status"`
	CanSend        bool            `json:"can_send"`
}

type UnreadSummaryResp struct {
	NotificationUnread int64 `json:"notification_unread"`
	ConversationUnread int64 `json:"conversation_unread"`
	TotalUnread        int64 `json:"total_unread"`
}

type UserSendChatReq struct {
	RecipientId    int64  `json:"recipient_id,string,optional"`
	ConversationId int64  `json:"conversation_id,string,optional"`
	Content        string `json:"content"`
}
