// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: proto/article.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章业务状态（仅描述社区场景下的状态）
type ArticleStatus int32

const (
	ArticleStatus_ARTICLE_STATUS_UNSPECIFIED ArticleStatus = 0 // 未指定
	ArticleStatus_DRAFT                      ArticleStatus = 1 // 草稿
	ArticleStatus_PUBLISHED                  ArticleStatus = 2 // 已发布
	ArticleStatus_REVIEWING                  ArticleStatus = 3 // 审核中（社区必备）
	ArticleStatus_REJECTED                   ArticleStatus = 4 // 审核被拒
	ArticleStatus_DELETED                    ArticleStatus = 5 // 已删除（逻辑删除）
)

// Enum value maps for ArticleStatus.
var (
	ArticleStatus_name = map[int32]string{
		0: "ARTICLE_STATUS_UNSPECIFIED",
		1: "DRAFT",
		2: "PUBLISHED",
		3: "REVIEWING",
		4: "REJECTED",
		5: "DELETED",
	}
	ArticleStatus_value = map[string]int32{
		"ARTICLE_STATUS_UNSPECIFIED": 0,
		"DRAFT":                      1,
		"PUBLISHED":                  2,
		"REVIEWING":                  3,
		"REJECTED":                   4,
		"DELETED":                    5,
	}
)

func (x ArticleStatus) Enum() *ArticleStatus {
	p := new(ArticleStatus)
	*p = x
	return p
}

func (x ArticleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_article_proto_enumTypes[0].Descriptor()
}

func (ArticleStatus) Type() protoreflect.EnumType {
	return &file_proto_article_proto_enumTypes[0]
}

func (x ArticleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleStatus.Descriptor instead.
func (ArticleStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{0}
}

// 文章核心结构体（轻量 Markdown 格式，元数据+正文都存在 PG）
type Article struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                  // 文章唯一ID（雪花ID）
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                            // 文章标题
	Brief           string                 `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief,omitempty"`                                            // 文章摘要（自动截取/手动填写，用于列表展示）
	MarkdownContent string                 `protobuf:"bytes,4,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"` // 轻量 Markdown 正文（约束格式：标题、列表、图片链接、引用）
	CoverImageUrl   string                 `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`     // 封面图URL（用OSS/MinIO存储，仅存URL）
	ManualTypeTag   string                 `protobuf:"bytes,6,opt,name=manual_type_tag,json=manualTypeTag,proto3" json:"manual_type_tag,omitempty"`     // 手动一级标签（如：游戏评测/攻略/杂谈）
	SecondaryTags   []string               `protobuf:"bytes,7,rep,name=secondary_tags,json=secondaryTags,proto3" json:"secondary_tags,omitempty"`       // 二级标签（如：《黑神话：悟空》/PS5/Steam）
	AuthorId        string                 `protobuf:"bytes,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                      // 作者ID（关联用户服务）
	CreateTime      int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`               // 创建时间（毫秒时间戳）
	UpdateTime      int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`              // 更新时间（毫秒时间戳）
	Status          ArticleStatus          `protobuf:"varint,11,opt,name=status,proto3,enum=article.ArticleStatus" json:"status,omitempty"`             // 文章状态
	// 社区互动数据（直接存在PG，高频更新可缓存）
	ViewCount     int32             `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`                                                                    // 阅读量
	LikeCount     int32             `protobuf:"varint,13,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`                                                                    // 点赞数
	CommentCount  int32             `protobuf:"varint,14,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`                                                           // 评论数
	ShareCount    int32             `protobuf:"varint,15,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`                                                                 // 分享数
	ExtInfo       map[string]string `protobuf:"bytes,16,rep,name=ext_info,json=extInfo,proto3" json:"ext_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段（如：关联游戏ID/活动ID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_proto_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *Article) GetMarkdownContent() string {
	if x != nil {
		return x.MarkdownContent
	}
	return ""
}

func (x *Article) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Article) GetManualTypeTag() string {
	if x != nil {
		return x.ManualTypeTag
	}
	return ""
}

func (x *Article) GetSecondaryTags() []string {
	if x != nil {
		return x.SecondaryTags
	}
	return nil
}

func (x *Article) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Article) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Article) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Article) GetStatus() ArticleStatus {
	if x != nil {
		return x.Status
	}
	return ArticleStatus_ARTICLE_STATUS_UNSPECIFIED
}

func (x *Article) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Article) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Article) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Article) GetShareCount() int32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Article) GetExtInfo() map[string]string {
	if x != nil {
		return x.ExtInfo
	}
	return nil
}

// 创建文章请求
type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                              // 标题
	Brief         *string                `protobuf:"bytes,2,opt,name=brief,proto3,oneof" json:"brief,omitempty"`                                        // 摘要（可选，自动截取正文前150字）
	ContentPath   string                 `protobuf:"bytes,3,opt,name=content_path,json=contentPath,proto3" json:"content_path,omitempty"`               // MinIO 中的文件路径（前端直传后返回的 objectName）
	CoverImageUrl *string                `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"` // 封面图URL（可选）
	ManualTypeTag string                 `protobuf:"bytes,5,opt,name=manual_type_tag,json=manualTypeTag,proto3" json:"manual_type_tag,omitempty"`       // 一级标签
	SecondaryTags []string               `protobuf:"bytes,6,rep,name=secondary_tags,json=secondaryTags,proto3" json:"secondary_tags,omitempty"`         // 二级标签
	AuthorId      string                 `protobuf:"bytes,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                        // 作者ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_proto_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetBrief() string {
	if x != nil && x.Brief != nil {
		return *x.Brief
	}
	return ""
}

func (x *CreateArticleRequest) GetContentPath() string {
	if x != nil {
		return x.ContentPath
	}
	return ""
}

func (x *CreateArticleRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *CreateArticleRequest) GetManualTypeTag() string {
	if x != nil {
		return x.ManualTypeTag
	}
	return ""
}

func (x *CreateArticleRequest) GetSecondaryTags() []string {
	if x != nil {
		return x.SecondaryTags
	}
	return nil
}

func (x *CreateArticleRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

// 创建文章响应
type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_proto_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResponse) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

// 获取文章详情请求
type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID
	IncrView      bool                   `protobuf:"varint,2,opt,name=incr_view,json=incrView,proto3" json:"incr_view,omitempty"`   // 是否增加阅读量（详情页传true，其他场景传false）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_proto_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *GetArticleRequest) GetIncrView() bool {
	if x != nil {
		return x.IncrView
	}
	return false
}

// 获取文章详情响应
type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"` // 文章完整数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_proto_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// 更新文章请求
type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID（必传）
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Brief         *string                `protobuf:"bytes,3,opt,name=brief,proto3,oneof" json:"brief,omitempty"`
	ContentPath   *string                `protobuf:"bytes,4,opt,name=content_path,json=contentPath,proto3,oneof" json:"content_path,omitempty"`
	CoverImageUrl *string                `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	ManualTypeTag *string                `protobuf:"bytes,6,opt,name=manual_type_tag,json=manualTypeTag,proto3,oneof" json:"manual_type_tag,omitempty"`
	SecondaryTags []string               `protobuf:"bytes,7,rep,name=secondary_tags,json=secondaryTags,proto3" json:"secondary_tags,omitempty"`
	Status        *ArticleStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=article.ArticleStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_proto_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetBrief() string {
	if x != nil && x.Brief != nil {
		return *x.Brief
	}
	return ""
}

func (x *UpdateArticleRequest) GetContentPath() string {
	if x != nil && x.ContentPath != nil {
		return *x.ContentPath
	}
	return ""
}

func (x *UpdateArticleRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *UpdateArticleRequest) GetManualTypeTag() string {
	if x != nil && x.ManualTypeTag != nil {
		return *x.ManualTypeTag
	}
	return ""
}

func (x *UpdateArticleRequest) GetSecondaryTags() []string {
	if x != nil {
		return x.SecondaryTags
	}
	return nil
}

func (x *UpdateArticleRequest) GetStatus() ArticleStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ArticleStatus_ARTICLE_STATUS_UNSPECIFIED
}

// 更新文章响应
type UpdateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResponse) Reset() {
	*x = UpdateArticleResponse{}
	mi := &file_proto_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResponse) ProtoMessage() {}

func (x *UpdateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResponse.ProtoReflect.Descriptor instead.
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除文章请求
type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`    // 文章ID
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作人ID（作者/管理员）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_proto_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *DeleteArticleRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

// 删除文章响应
type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_proto_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 文章列表查询请求（社区核心场景：首页/标签页/个人主页）
type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManualTypeTag *string                `protobuf:"bytes,1,opt,name=manual_type_tag,json=manualTypeTag,proto3,oneof" json:"manual_type_tag,omitempty"` // 按一级标签筛选
	SecondaryTag  *string                `protobuf:"bytes,2,opt,name=secondary_tag,json=secondaryTag,proto3,oneof" json:"secondary_tag,omitempty"`      // 按二级标签筛选
	RelatedGameId *string                `protobuf:"bytes,3,opt,name=related_game_id,json=relatedGameId,proto3,oneof" json:"related_game_id,omitempty"` // 按关联游戏筛选
	AuthorId      *string                `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3,oneof" json:"author_id,omitempty"`                  // 按作者筛选
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`                                               // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                       // 每页数量
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                              // 排序字段（create_time/like_count/comment_count）
	Desc          bool                   `protobuf:"varint,8,opt,name=desc,proto3" json:"desc,omitempty"`                                               // 是否降序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_proto_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{9}
}

func (x *ListArticlesRequest) GetManualTypeTag() string {
	if x != nil && x.ManualTypeTag != nil {
		return *x.ManualTypeTag
	}
	return ""
}

func (x *ListArticlesRequest) GetSecondaryTag() string {
	if x != nil && x.SecondaryTag != nil {
		return *x.SecondaryTag
	}
	return ""
}

func (x *ListArticlesRequest) GetRelatedGameId() string {
	if x != nil && x.RelatedGameId != nil {
		return *x.RelatedGameId
	}
	return ""
}

func (x *ListArticlesRequest) GetAuthorId() string {
	if x != nil && x.AuthorId != nil {
		return *x.AuthorId
	}
	return ""
}

func (x *ListArticlesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArticlesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListArticlesRequest) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// 文章列表查询响应
type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`                  // 文章列表（仅返回列表展示所需字段，可在服务层裁剪）
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总条数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_proto_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{10}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListArticlesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 图片上传
type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=fileUrl,proto3" json:"fileUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{12}
}

func (x *UploadFileResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

// 获取直传预签名 URL 请求
type GetPresignedUploadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // 文件名（如：xxx.md）
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME 类型（如：text/markdown）
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`          // 申请人ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUploadUrlRequest) Reset() {
	*x = GetPresignedUploadUrlRequest{}
	mi := &file_proto_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUploadUrlRequest) ProtoMessage() {}

func (x *GetPresignedUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{13}
}

func (x *GetPresignedUploadUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetPresignedUploadUrlRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetPresignedUploadUrlRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

// 获取直传预签名 URL 响应
type GetPresignedUploadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`    // 前端用来 PUT 的预签名 URL
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"` // MinIO 中的相对路径（用于后续创建文章传给 content_path）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUploadUrlResponse) Reset() {
	*x = GetPresignedUploadUrlResponse{}
	mi := &file_proto_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUploadUrlResponse) ProtoMessage() {}

func (x *GetPresignedUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{14}
}

func (x *GetPresignedUploadUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetPresignedUploadUrlResponse) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

var File_proto_article_proto protoreflect.FileDescriptor

const file_proto_article_proto_rawDesc = "" +
	"\n" +
	"\x13proto/article.proto\x12\aarticle\"\xf0\x04\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05brief\x18\x03 \x01(\tR\x05brief\x12)\n" +
	"\x10markdown_content\x18\x04 \x01(\tR\x0fmarkdownContent\x12&\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tR\rcoverImageUrl\x12&\n" +
	"\x0fmanual_type_tag\x18\x06 \x01(\tR\rmanualTypeTag\x12%\n" +
	"\x0esecondary_tags\x18\a \x03(\tR\rsecondaryTags\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\tR\bauthorId\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\x12.\n" +
	"\x06status\x18\v \x01(\x0e2\x16.article.ArticleStatusR\x06status\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\r \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x0e \x01(\x05R\fcommentCount\x12\x1f\n" +
	"\vshare_count\x18\x0f \x01(\x05R\n" +
	"shareCount\x128\n" +
	"\bext_info\x18\x10 \x03(\v2\x1d.article.Article.ExtInfoEntryR\aextInfo\x1a:\n" +
	"\fExtInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x02\n" +
	"\x14CreateArticleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x19\n" +
	"\x05brief\x18\x02 \x01(\tH\x00R\x05brief\x88\x01\x01\x12!\n" +
	"\fcontent_path\x18\x03 \x01(\tR\vcontentPath\x12+\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tH\x01R\rcoverImageUrl\x88\x01\x01\x12&\n" +
	"\x0fmanual_type_tag\x18\x05 \x01(\tR\rmanualTypeTag\x12%\n" +
	"\x0esecondary_tags\x18\x06 \x03(\tR\rsecondaryTags\x12\x1b\n" +
	"\tauthor_id\x18\a \x01(\tR\bauthorIdB\b\n" +
	"\x06_briefB\x12\n" +
	"\x10_cover_image_url\"6\n" +
	"\x15CreateArticleResponse\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"O\n" +
	"\x11GetArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1b\n" +
	"\tincr_view\x18\x02 \x01(\bR\bincrView\"@\n" +
	"\x12GetArticleResponse\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\"\xa1\x03\n" +
	"\x14UpdateArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x19\n" +
	"\x05brief\x18\x03 \x01(\tH\x01R\x05brief\x88\x01\x01\x12&\n" +
	"\fcontent_path\x18\x04 \x01(\tH\x02R\vcontentPath\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tH\x03R\rcoverImageUrl\x88\x01\x01\x12+\n" +
	"\x0fmanual_type_tag\x18\x06 \x01(\tH\x04R\rmanualTypeTag\x88\x01\x01\x12%\n" +
	"\x0esecondary_tags\x18\a \x03(\tR\rsecondaryTags\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x16.article.ArticleStatusH\x05R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\b\n" +
	"\x06_briefB\x0f\n" +
	"\r_content_pathB\x12\n" +
	"\x10_cover_image_urlB\x12\n" +
	"\x10_manual_type_tagB\t\n" +
	"\a_status\"1\n" +
	"\x15UpdateArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x14DeleteArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\"1\n" +
	"\x15DeleteArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe1\x02\n" +
	"\x13ListArticlesRequest\x12+\n" +
	"\x0fmanual_type_tag\x18\x01 \x01(\tH\x00R\rmanualTypeTag\x88\x01\x01\x12(\n" +
	"\rsecondary_tag\x18\x02 \x01(\tH\x01R\fsecondaryTag\x88\x01\x01\x12+\n" +
	"\x0frelated_game_id\x18\x03 \x01(\tH\x02R\rrelatedGameId\x88\x01\x01\x12 \n" +
	"\tauthor_id\x18\x04 \x01(\tH\x03R\bauthorId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x12\n" +
	"\x04desc\x18\b \x01(\bR\x04descB\x12\n" +
	"\x10_manual_type_tagB\x10\n" +
	"\x0e_secondary_tagB\x12\n" +
	"\x10_related_game_idB\f\n" +
	"\n" +
	"_author_id\"\x8b\x01\n" +
	"\x14ListArticlesResponse\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.article.ArticleR\barticles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"I\n" +
	"\x11UploadFileRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\".\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\afileUrl\x18\x01 \x01(\tR\afileUrl\"{\n" +
	"\x1cGetPresignedUploadUrlRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\"_\n" +
	"\x1dGetPresignedUploadUrlResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName*s\n" +
	"\rArticleStatus\x12\x1e\n" +
	"\x1aARTICLE_STATUS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\r\n" +
	"\tPUBLISHED\x10\x02\x12\r\n" +
	"\tREVIEWING\x10\x03\x12\f\n" +
	"\bREJECTED\x10\x04\x12\v\n" +
	"\aDELETED\x10\x052\xc3\x04\n" +
	"\x0eArticleService\x12N\n" +
	"\rCreateArticle\x12\x1d.article.CreateArticleRequest\x1a\x1e.article.CreateArticleResponse\x12E\n" +
	"\n" +
	"GetArticle\x12\x1a.article.GetArticleRequest\x1a\x1b.article.GetArticleResponse\x12N\n" +
	"\rUpdateArticle\x12\x1d.article.UpdateArticleRequest\x1a\x1e.article.UpdateArticleResponse\x12N\n" +
	"\rDeleteArticle\x12\x1d.article.DeleteArticleRequest\x1a\x1e.article.DeleteArticleResponse\x12K\n" +
	"\fListArticles\x12\x1c.article.ListArticlesRequest\x1a\x1d.article.ListArticlesResponse\x12E\n" +
	"\n" +
	"UploadFile\x12\x1a.article.UploadFileRequest\x1a\x1b.article.UploadFileResponse\x12f\n" +
	"\x15GetPresignedUploadUrl\x12%.article.GetPresignedUploadUrlRequest\x1a&.article.GetPresignedUploadUrlResponseB\x03Z\x01.b\x06proto3"

var (
	file_proto_article_proto_rawDescOnce sync.Once
	file_proto_article_proto_rawDescData []byte
)

func file_proto_article_proto_rawDescGZIP() []byte {
	file_proto_article_proto_rawDescOnce.Do(func() {
		file_proto_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_article_proto_rawDesc), len(file_proto_article_proto_rawDesc)))
	})
	return file_proto_article_proto_rawDescData
}

var file_proto_article_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_article_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_article_proto_goTypes = []any{
	(ArticleStatus)(0),                    // 0: article.ArticleStatus
	(*Article)(nil),                       // 1: article.Article
	(*CreateArticleRequest)(nil),          // 2: article.CreateArticleRequest
	(*CreateArticleResponse)(nil),         // 3: article.CreateArticleResponse
	(*GetArticleRequest)(nil),             // 4: article.GetArticleRequest
	(*GetArticleResponse)(nil),            // 5: article.GetArticleResponse
	(*UpdateArticleRequest)(nil),          // 6: article.UpdateArticleRequest
	(*UpdateArticleResponse)(nil),         // 7: article.UpdateArticleResponse
	(*DeleteArticleRequest)(nil),          // 8: article.DeleteArticleRequest
	(*DeleteArticleResponse)(nil),         // 9: article.DeleteArticleResponse
	(*ListArticlesRequest)(nil),           // 10: article.ListArticlesRequest
	(*ListArticlesResponse)(nil),          // 11: article.ListArticlesResponse
	(*UploadFileRequest)(nil),             // 12: article.UploadFileRequest
	(*UploadFileResponse)(nil),            // 13: article.UploadFileResponse
	(*GetPresignedUploadUrlRequest)(nil),  // 14: article.GetPresignedUploadUrlRequest
	(*GetPresignedUploadUrlResponse)(nil), // 15: article.GetPresignedUploadUrlResponse
	nil,                                   // 16: article.Article.ExtInfoEntry
}
var file_proto_article_proto_depIdxs = []int32{
	0,  // 0: article.Article.status:type_name -> article.ArticleStatus
	16, // 1: article.Article.ext_info:type_name -> article.Article.ExtInfoEntry
	1,  // 2: article.GetArticleResponse.article:type_name -> article.Article
	0,  // 3: article.UpdateArticleRequest.status:type_name -> article.ArticleStatus
	1,  // 4: article.ListArticlesResponse.articles:type_name -> article.Article
	2,  // 5: article.ArticleService.CreateArticle:input_type -> article.CreateArticleRequest
	4,  // 6: article.ArticleService.GetArticle:input_type -> article.GetArticleRequest
	6,  // 7: article.ArticleService.UpdateArticle:input_type -> article.UpdateArticleRequest
	8,  // 8: article.ArticleService.DeleteArticle:input_type -> article.DeleteArticleRequest
	10, // 9: article.ArticleService.ListArticles:input_type -> article.ListArticlesRequest
	12, // 10: article.ArticleService.UploadFile:input_type -> article.UploadFileRequest
	14, // 11: article.ArticleService.GetPresignedUploadUrl:input_type -> article.GetPresignedUploadUrlRequest
	3,  // 12: article.ArticleService.CreateArticle:output_type -> article.CreateArticleResponse
	5,  // 13: article.ArticleService.GetArticle:output_type -> article.GetArticleResponse
	7,  // 14: article.ArticleService.UpdateArticle:output_type -> article.UpdateArticleResponse
	9,  // 15: article.ArticleService.DeleteArticle:output_type -> article.DeleteArticleResponse
	11, // 16: article.ArticleService.ListArticles:output_type -> article.ListArticlesResponse
	13, // 17: article.ArticleService.UploadFile:output_type -> article.UploadFileResponse
	15, // 18: article.ArticleService.GetPresignedUploadUrl:output_type -> article.GetPresignedUploadUrlResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_article_proto_init() }
func file_proto_article_proto_init() {
	if File_proto_article_proto != nil {
		return
	}
	file_proto_article_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_article_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_article_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_article_proto_rawDesc), len(file_proto_article_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_article_proto_goTypes,
		DependencyIndexes: file_proto_article_proto_depIdxs,
		EnumInfos:         file_proto_article_proto_enumTypes,
		MessageInfos:      file_proto_article_proto_msgTypes,
	}.Build()
	File_proto_article_proto = out.File
	file_proto_article_proto_goTypes = nil
	file_proto_article_proto_depIdxs = nil
}
