// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationKind int32

const (
	NotificationKind_NOTIFICATION_KIND_UNSPECIFIED NotificationKind = 0
	NotificationKind_ADMIN_BROADCAST               NotificationKind = 1
	NotificationKind_ADMIN_NOTICE                  NotificationKind = 2
	NotificationKind_ARTICLE_COMMENT               NotificationKind = 3
	NotificationKind_COMMENT_REPLY                 NotificationKind = 4
	NotificationKind_ARTICLE_PUBLISHED             NotificationKind = 5
	NotificationKind_ARTICLE_LIKED                 NotificationKind = 6
)

// Enum value maps for NotificationKind.
var (
	NotificationKind_name = map[int32]string{
		0: "NOTIFICATION_KIND_UNSPECIFIED",
		1: "ADMIN_BROADCAST",
		2: "ADMIN_NOTICE",
		3: "ARTICLE_COMMENT",
		4: "COMMENT_REPLY",
		5: "ARTICLE_PUBLISHED",
		6: "ARTICLE_LIKED",
	}
	NotificationKind_value = map[string]int32{
		"NOTIFICATION_KIND_UNSPECIFIED": 0,
		"ADMIN_BROADCAST":               1,
		"ADMIN_NOTICE":                  2,
		"ARTICLE_COMMENT":               3,
		"COMMENT_REPLY":                 4,
		"ARTICLE_PUBLISHED":             5,
		"ARTICLE_LIKED":                 6,
	}
)

func (x NotificationKind) Enum() *NotificationKind {
	p := new(NotificationKind)
	*p = x
	return p
}

func (x NotificationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[0].Descriptor()
}

func (NotificationKind) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[0]
}

func (x NotificationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationKind.Descriptor instead.
func (NotificationKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

type SenderRole int32

const (
	SenderRole_SENDER_ROLE_UNSPECIFIED SenderRole = 0
	SenderRole_USER                    SenderRole = 1
	SenderRole_ADMIN                   SenderRole = 2
	SenderRole_SYSTEM                  SenderRole = 3
)

// Enum value maps for SenderRole.
var (
	SenderRole_name = map[int32]string{
		0: "SENDER_ROLE_UNSPECIFIED",
		1: "USER",
		2: "ADMIN",
		3: "SYSTEM",
	}
	SenderRole_value = map[string]int32{
		"SENDER_ROLE_UNSPECIFIED": 0,
		"USER":                    1,
		"ADMIN":                   2,
		"SYSTEM":                  3,
	}
)

func (x SenderRole) Enum() *SenderRole {
	p := new(SenderRole)
	*p = x
	return p
}

func (x SenderRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[1].Descriptor()
}

func (SenderRole) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[1]
}

func (x SenderRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderRole.Descriptor instead.
func (SenderRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

type ConversationStatus int32

const (
	ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED ConversationStatus = 0
	ConversationStatus_PENDING                         ConversationStatus = 1
	ConversationStatus_OPEN                            ConversationStatus = 2
)

// Enum value maps for ConversationStatus.
var (
	ConversationStatus_name = map[int32]string{
		0: "CONVERSATION_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "OPEN",
	}
	ConversationStatus_value = map[string]int32{
		"CONVERSATION_STATUS_UNSPECIFIED": 0,
		"PENDING":                         1,
		"OPEN":                            2,
	}
)

func (x ConversationStatus) Enum() *ConversationStatus {
	p := new(ConversationStatus)
	*p = x
	return p
}

func (x ConversationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[2].Descriptor()
}

func (ConversationStatus) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[2]
}

func (x ConversationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationStatus.Descriptor instead.
func (ConversationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type NotificationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipientId   int64                  `protobuf:"varint,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderRole    SenderRole             `protobuf:"varint,4,opt,name=sender_role,json=senderRole,proto3,enum=message.SenderRole" json:"sender_role,omitempty"`
	Kind          NotificationKind       `protobuf:"varint,5,opt,name=kind,proto3,enum=message.NotificationKind" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	IsRead        bool                   `protobuf:"varint,8,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,10,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationItem) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *NotificationItem) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *NotificationItem) GetSenderRole() SenderRole {
	if x != nil {
		return x.SenderRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *NotificationItem) GetKind() NotificationKind {
	if x != nil {
		return x.Kind
	}
	return NotificationKind_NOTIFICATION_KIND_UNSPECIFIED
}

func (x *NotificationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NotificationItem) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type NotificationListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	UnreadOnly    bool                   `protobuf:"varint,4,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationListReq) Reset() {
	*x = NotificationListReq{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationListReq) ProtoMessage() {}

func (x *NotificationListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationListReq.ProtoReflect.Descriptor instead.
func (*NotificationListReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NotificationListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NotificationListReq) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

type NotificationListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Items         []*NotificationItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationListResp) Reset() {
	*x = NotificationListResp{}
	mi := &file_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationListResp) ProtoMessage() {}

func (x *NotificationListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationListResp.ProtoReflect.Descriptor instead.
func (*NotificationListResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NotificationListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NotificationListResp) GetItems() []*NotificationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *NotificationListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NotificationListResp) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type MarkNotificationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationId int64                  `protobuf:"varint,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationReq) Reset() {
	*x = MarkNotificationReq{}
	mi := &file_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReq) ProtoMessage() {}

func (x *MarkNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReq.ProtoReflect.Descriptor instead.
func (*MarkNotificationReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *MarkNotificationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkNotificationReq) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type MarkAllNotificationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReq) Reset() {
	*x = MarkAllNotificationsReq{}
	mi := &file_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReq) ProtoMessage() {}

func (x *MarkAllNotificationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReq.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAllNotificationsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnreadSummaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadSummaryReq) Reset() {
	*x = UnreadSummaryReq{}
	mi := &file_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadSummaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadSummaryReq) ProtoMessage() {}

func (x *UnreadSummaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadSummaryReq.ProtoReflect.Descriptor instead.
func (*UnreadSummaryReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *UnreadSummaryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnreadSummaryResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Code               int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	NotificationUnread int64                  `protobuf:"varint,3,opt,name=notification_unread,json=notificationUnread,proto3" json:"notification_unread,omitempty"`
	ConversationUnread int64                  `protobuf:"varint,4,opt,name=conversation_unread,json=conversationUnread,proto3" json:"conversation_unread,omitempty"`
	TotalUnread        int64                  `protobuf:"varint,5,opt,name=total_unread,json=totalUnread,proto3" json:"total_unread,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UnreadSummaryResp) Reset() {
	*x = UnreadSummaryResp{}
	mi := &file_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadSummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadSummaryResp) ProtoMessage() {}

func (x *UnreadSummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadSummaryResp.ProtoReflect.Descriptor instead.
func (*UnreadSummaryResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *UnreadSummaryResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnreadSummaryResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UnreadSummaryResp) GetNotificationUnread() int64 {
	if x != nil {
		return x.NotificationUnread
	}
	return 0
}

func (x *UnreadSummaryResp) GetConversationUnread() int64 {
	if x != nil {
		return x.ConversationUnread
	}
	return 0
}

func (x *UnreadSummaryResp) GetTotalUnread() int64 {
	if x != nil {
		return x.TotalUnread
	}
	return 0
}

type SendNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientIds  []int64                `protobuf:"varint,1,rep,packed,name=recipient_ids,json=recipientIds,proto3" json:"recipient_ids,omitempty"`
	Broadcast     bool                   `protobuf:"varint,2,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderRole    SenderRole             `protobuf:"varint,4,opt,name=sender_role,json=senderRole,proto3,enum=message.SenderRole" json:"sender_role,omitempty"`
	Kind          NotificationKind       `protobuf:"varint,5,opt,name=kind,proto3,enum=message.NotificationKind" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationReq) Reset() {
	*x = SendNotificationReq{}
	mi := &file_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationReq) ProtoMessage() {}

func (x *SendNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationReq.ProtoReflect.Descriptor instead.
func (*SendNotificationReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *SendNotificationReq) GetRecipientIds() []int64 {
	if x != nil {
		return x.RecipientIds
	}
	return nil
}

func (x *SendNotificationReq) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *SendNotificationReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendNotificationReq) GetSenderRole() SenderRole {
	if x != nil {
		return x.SenderRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *SendNotificationReq) GetKind() NotificationKind {
	if x != nil {
		return x.Kind
	}
	return NotificationKind_NOTIFICATION_KIND_UNSPECIFIED
}

func (x *SendNotificationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNotificationReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendNotificationReq) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type SendNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Affected      int64                  `protobuf:"varint,3,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResp) Reset() {
	*x = SendNotificationResp{}
	mi := &file_proto_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResp) ProtoMessage() {}

func (x *SendNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResp.ProtoReflect.Descriptor instead.
func (*SendNotificationResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{9}
}

func (x *SendNotificationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendNotificationResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendNotificationResp) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type ConversationItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PeerId          int64                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerRole        SenderRole             `protobuf:"varint,3,opt,name=peer_role,json=peerRole,proto3,enum=message.SenderRole" json:"peer_role,omitempty"`
	PeerName        string                 `protobuf:"bytes,4,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	PeerEmail       string                 `protobuf:"bytes,5,opt,name=peer_email,json=peerEmail,proto3" json:"peer_email,omitempty"`
	Status          ConversationStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=message.ConversationStatus" json:"status,omitempty"`
	UnreadCount     int64                  `protobuf:"varint,7,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	LatestMessage   string                 `protobuf:"bytes,8,opt,name=latest_message,json=latestMessage,proto3" json:"latest_message,omitempty"`
	LatestMessageAt int64                  `protobuf:"varint,9,opt,name=latest_message_at,json=latestMessageAt,proto3" json:"latest_message_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CanSend         bool                   `protobuf:"varint,11,opt,name=can_send,json=canSend,proto3" json:"can_send,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConversationItem) Reset() {
	*x = ConversationItem{}
	mi := &file_proto_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationItem) ProtoMessage() {}

func (x *ConversationItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationItem.ProtoReflect.Descriptor instead.
func (*ConversationItem) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *ConversationItem) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ConversationItem) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *ConversationItem) GetPeerRole() SenderRole {
	if x != nil {
		return x.PeerRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *ConversationItem) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *ConversationItem) GetPeerEmail() string {
	if x != nil {
		return x.PeerEmail
	}
	return ""
}

func (x *ConversationItem) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED
}

func (x *ConversationItem) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationItem) GetLatestMessage() string {
	if x != nil {
		return x.LatestMessage
	}
	return ""
}

func (x *ConversationItem) GetLatestMessageAt() int64 {
	if x != nil {
		return x.LatestMessageAt
	}
	return 0
}

func (x *ConversationItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ConversationItem) GetCanSend() bool {
	if x != nil {
		return x.CanSend
	}
	return false
}

type ConversationListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    int64                  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorRole  SenderRole             `protobuf:"varint,2,opt,name=operator_role,json=operatorRole,proto3,enum=message.SenderRole" json:"operator_role,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationListReq) Reset() {
	*x = ConversationListReq{}
	mi := &file_proto_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationListReq) ProtoMessage() {}

func (x *ConversationListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationListReq.ProtoReflect.Descriptor instead.
func (*ConversationListReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{11}
}

func (x *ConversationListReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *ConversationListReq) GetOperatorRole() SenderRole {
	if x != nil {
		return x.OperatorRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *ConversationListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConversationListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ConversationListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Items         []*ConversationItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationListResp) Reset() {
	*x = ConversationListResp{}
	mi := &file_proto_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationListResp) ProtoMessage() {}

func (x *ConversationListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationListResp.ProtoReflect.Descriptor instead.
func (*ConversationListResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{12}
}

func (x *ConversationListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConversationListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConversationListResp) GetItems() []*ConversationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ConversationListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ConversationListResp) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ChatMessageItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderRole     SenderRole             `protobuf:"varint,4,opt,name=sender_role,json=senderRole,proto3,enum=message.SenderRole" json:"sender_role,omitempty"`
	RecipientId    int64                  `protobuf:"varint,5,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	RecipientRole  SenderRole             `protobuf:"varint,6,opt,name=recipient_role,json=recipientRole,proto3,enum=message.SenderRole" json:"recipient_role,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	IsRead         bool                   `protobuf:"varint,8,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatMessageItem) Reset() {
	*x = ChatMessageItem{}
	mi := &file_proto_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageItem) ProtoMessage() {}

func (x *ChatMessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageItem.ProtoReflect.Descriptor instead.
func (*ChatMessageItem) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{13}
}

func (x *ChatMessageItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatMessageItem) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ChatMessageItem) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessageItem) GetSenderRole() SenderRole {
	if x != nil {
		return x.SenderRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *ChatMessageItem) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *ChatMessageItem) GetRecipientRole() SenderRole {
	if x != nil {
		return x.RecipientRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *ChatMessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *ChatMessageItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ConversationMessageListReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperatorId     int64                  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorRole   SenderRole             `protobuf:"varint,2,opt,name=operator_role,json=operatorRole,proto3,enum=message.SenderRole" json:"operator_role,omitempty"`
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Offset         int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationMessageListReq) Reset() {
	*x = ConversationMessageListReq{}
	mi := &file_proto_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessageListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessageListReq) ProtoMessage() {}

func (x *ConversationMessageListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessageListReq.ProtoReflect.Descriptor instead.
func (*ConversationMessageListReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{14}
}

func (x *ConversationMessageListReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *ConversationMessageListReq) GetOperatorRole() SenderRole {
	if x != nil {
		return x.OperatorRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *ConversationMessageListReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ConversationMessageListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConversationMessageListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ConversationMessageListResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg               string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Items             []*ChatMessageItem     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Status            ConversationStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=message.ConversationStatus" json:"status,omitempty"`
	CanSend           bool                   `protobuf:"varint,5,opt,name=can_send,json=canSend,proto3" json:"can_send,omitempty"`
	PendingSenderId   int64                  `protobuf:"varint,6,opt,name=pending_sender_id,json=pendingSenderId,proto3" json:"pending_sender_id,omitempty"`
	PendingSenderRole SenderRole             `protobuf:"varint,7,opt,name=pending_sender_role,json=pendingSenderRole,proto3,enum=message.SenderRole" json:"pending_sender_role,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationMessageListResp) Reset() {
	*x = ConversationMessageListResp{}
	mi := &file_proto_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessageListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessageListResp) ProtoMessage() {}

func (x *ConversationMessageListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessageListResp.ProtoReflect.Descriptor instead.
func (*ConversationMessageListResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{15}
}

func (x *ConversationMessageListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConversationMessageListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConversationMessageListResp) GetItems() []*ChatMessageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ConversationMessageListResp) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED
}

func (x *ConversationMessageListResp) GetCanSend() bool {
	if x != nil {
		return x.CanSend
	}
	return false
}

func (x *ConversationMessageListResp) GetPendingSenderId() int64 {
	if x != nil {
		return x.PendingSenderId
	}
	return 0
}

func (x *ConversationMessageListResp) GetPendingSenderRole() SenderRole {
	if x != nil {
		return x.PendingSenderRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

type SendChatMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderRole     SenderRole             `protobuf:"varint,2,opt,name=sender_role,json=senderRole,proto3,enum=message.SenderRole" json:"sender_role,omitempty"`
	RecipientId    int64                  `protobuf:"varint,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	RecipientRole  SenderRole             `protobuf:"varint,4,opt,name=recipient_role,json=recipientRole,proto3,enum=message.SenderRole" json:"recipient_role,omitempty"`
	ConversationId int64                  `protobuf:"varint,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendChatMessageReq) Reset() {
	*x = SendChatMessageReq{}
	mi := &file_proto_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageReq) ProtoMessage() {}

func (x *SendChatMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageReq.ProtoReflect.Descriptor instead.
func (*SendChatMessageReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{16}
}

func (x *SendChatMessageReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendChatMessageReq) GetSenderRole() SenderRole {
	if x != nil {
		return x.SenderRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *SendChatMessageReq) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *SendChatMessageReq) GetRecipientRole() SenderRole {
	if x != nil {
		return x.RecipientRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *SendChatMessageReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendChatMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendChatMessageResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Message        *ChatMessageItem       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status         ConversationStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=message.ConversationStatus" json:"status,omitempty"`
	CanSend        bool                   `protobuf:"varint,6,opt,name=can_send,json=canSend,proto3" json:"can_send,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendChatMessageResp) Reset() {
	*x = SendChatMessageResp{}
	mi := &file_proto_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageResp) ProtoMessage() {}

func (x *SendChatMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageResp.ProtoReflect.Descriptor instead.
func (*SendChatMessageResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{17}
}

func (x *SendChatMessageResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendChatMessageResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendChatMessageResp) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendChatMessageResp) GetMessage() *ChatMessageItem {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendChatMessageResp) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED
}

func (x *SendChatMessageResp) GetCanSend() bool {
	if x != nil {
		return x.CanSend
	}
	return false
}

type MarkConversationReadReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperatorId     int64                  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorRole   SenderRole             `protobuf:"varint,2,opt,name=operator_role,json=operatorRole,proto3,enum=message.SenderRole" json:"operator_role,omitempty"`
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkConversationReadReq) Reset() {
	*x = MarkConversationReadReq{}
	mi := &file_proto_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConversationReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConversationReadReq) ProtoMessage() {}

func (x *MarkConversationReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConversationReadReq.ProtoReflect.Descriptor instead.
func (*MarkConversationReadReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{18}
}

func (x *MarkConversationReadReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *MarkConversationReadReq) GetOperatorRole() SenderRole {
	if x != nil {
		return x.OperatorRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *MarkConversationReadReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\amessage\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xa5\x03\n" +
	"\x10NotificationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\x03R\vrecipientId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x124\n" +
	"\vsender_role\x18\x04 \x01(\x0e2\x13.message.SenderRoleR\n" +
	"senderRole\x12-\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x19.message.NotificationKindR\x04kind\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x17\n" +
	"\ais_read\x18\b \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12:\n" +
	"\x05extra\x18\n" +
	" \x03(\v2$.message.NotificationItem.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x13NotificationListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vunread_only\x18\x04 \x01(\bR\n" +
	"unreadOnly\"\xa6\x01\n" +
	"\x14NotificationListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\x05items\x18\x03 \x03(\v2\x19.message.NotificationItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12!\n" +
	"\funread_count\x18\x05 \x01(\x03R\vunreadCount\"W\n" +
	"\x13MarkNotificationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\x03R\x0enotificationId\"2\n" +
	"\x17MarkAllNotificationsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"+\n" +
	"\x10UnreadSummaryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xbe\x01\n" +
	"\x11UnreadSummaryResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\x13notification_unread\x18\x03 \x01(\x03R\x12notificationUnread\x12/\n" +
	"\x13conversation_unread\x18\x04 \x01(\x03R\x12conversationUnread\x12!\n" +
	"\ftotal_unread\x18\x05 \x01(\x03R\vtotalUnread\"\x83\x03\n" +
	"\x13SendNotificationReq\x12#\n" +
	"\rrecipient_ids\x18\x01 \x03(\x03R\frecipientIds\x12\x1c\n" +
	"\tbroadcast\x18\x02 \x01(\bR\tbroadcast\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x124\n" +
	"\vsender_role\x18\x04 \x01(\x0e2\x13.message.SenderRoleR\n" +
	"senderRole\x12-\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x19.message.NotificationKindR\x04kind\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12=\n" +
	"\x05extra\x18\b \x03(\v2'.message.SendNotificationReq.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x14SendNotificationResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\baffected\x18\x03 \x01(\x03R\baffected\"\xa7\x03\n" +
	"\x10ConversationItem\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x03R\x06peerId\x120\n" +
	"\tpeer_role\x18\x03 \x01(\x0e2\x13.message.SenderRoleR\bpeerRole\x12\x1b\n" +
	"\tpeer_name\x18\x04 \x01(\tR\bpeerName\x12\x1d\n" +
	"\n" +
	"peer_email\x18\x05 \x01(\tR\tpeerEmail\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.message.ConversationStatusR\x06status\x12!\n" +
	"\funread_count\x18\a \x01(\x03R\vunreadCount\x12%\n" +
	"\x0elatest_message\x18\b \x01(\tR\rlatestMessage\x12*\n" +
	"\x11latest_message_at\x18\t \x01(\x03R\x0flatestMessageAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x19\n" +
	"\bcan_send\x18\v \x01(\bR\acanSend\"\x9e\x01\n" +
	"\x13ConversationListReq\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x128\n" +
	"\roperator_role\x18\x02 \x01(\x0e2\x13.message.SenderRoleR\foperatorRole\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xa6\x01\n" +
	"\x14ConversationListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\x05items\x18\x03 \x03(\v2\x19.message.ConversationItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12!\n" +
	"\funread_count\x18\x05 \x01(\x03R\vunreadCount\"\xce\x02\n" +
	"\x0fChatMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x124\n" +
	"\vsender_role\x18\x04 \x01(\x0e2\x13.message.SenderRoleR\n" +
	"senderRole\x12!\n" +
	"\frecipient_id\x18\x05 \x01(\x03R\vrecipientId\x12:\n" +
	"\x0erecipient_role\x18\x06 \x01(\x0e2\x13.message.SenderRoleR\rrecipientRole\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x17\n" +
	"\ais_read\x18\b \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\xce\x01\n" +
	"\x1aConversationMessageListReq\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x128\n" +
	"\roperator_role\x18\x02 \x01(\x0e2\x13.message.SenderRoleR\foperatorRole\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xb4\x02\n" +
	"\x1bConversationMessageListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\x05items\x18\x03 \x03(\v2\x18.message.ChatMessageItemR\x05items\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.message.ConversationStatusR\x06status\x12\x19\n" +
	"\bcan_send\x18\x05 \x01(\bR\acanSend\x12*\n" +
	"\x11pending_sender_id\x18\x06 \x01(\x03R\x0fpendingSenderId\x12C\n" +
	"\x13pending_sender_role\x18\a \x01(\x0e2\x13.message.SenderRoleR\x11pendingSenderRole\"\x89\x02\n" +
	"\x12SendChatMessageReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x124\n" +
	"\vsender_role\x18\x02 \x01(\x0e2\x13.message.SenderRoleR\n" +
	"senderRole\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\x03R\vrecipientId\x12:\n" +
	"\x0erecipient_role\x18\x04 \x01(\x0e2\x13.message.SenderRoleR\rrecipientRole\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\x03R\x0econversationId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"\xe8\x01\n" +
	"\x13SendChatMessageResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x122\n" +
	"\amessage\x18\x04 \x01(\v2\x18.message.ChatMessageItemR\amessage\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.message.ConversationStatusR\x06status\x12\x19\n" +
	"\bcan_send\x18\x06 \x01(\bR\acanSend\"\x9d\x01\n" +
	"\x17MarkConversationReadReq\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x128\n" +
	"\roperator_role\x18\x02 \x01(\x0e2\x13.message.SenderRoleR\foperatorRole\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId*\xae\x01\n" +
	"\x10NotificationKind\x12!\n" +
	"\x1dNOTIFICATION_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fADMIN_BROADCAST\x10\x01\x12\x10\n" +
	"\fADMIN_NOTICE\x10\x02\x12\x13\n" +
	"\x0fARTICLE_COMMENT\x10\x03\x12\x11\n" +
	"\rCOMMENT_REPLY\x10\x04\x12\x15\n" +
	"\x11ARTICLE_PUBLISHED\x10\x05\x12\x11\n" +
	"\rARTICLE_LIKED\x10\x06*J\n" +
	"\n" +
	"SenderRole\x12\x1b\n" +
	"\x17SENDER_ROLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x03*P\n" +
	"\x12ConversationStatus\x12#\n" +
	"\x1fCONVERSATION_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04OPEN\x10\x022\xeb\x05\n" +
	"\x0eMessageService\x12O\n" +
	"\x10SendNotification\x12\x1c.message.SendNotificationReq\x1a\x1d.message.SendNotificationResp\x12P\n" +
	"\x11ListNotifications\x12\x1c.message.NotificationListReq\x1a\x1d.message.NotificationListResp\x12G\n" +
	"\x14MarkNotificationRead\x12\x1c.message.MarkNotificationReq\x1a\x11.message.BaseResp\x12O\n" +
	"\x18MarkAllNotificationsRead\x12 .message.MarkAllNotificationsReq\x1a\x11.message.BaseResp\x12I\n" +
	"\x10GetUnreadSummary\x12\x19.message.UnreadSummaryReq\x1a\x1a.message.UnreadSummaryResp\x12P\n" +
	"\x11ListConversations\x12\x1c.message.ConversationListReq\x1a\x1d.message.ConversationListResp\x12d\n" +
	"\x17GetConversationMessages\x12#.message.ConversationMessageListReq\x1a$.message.ConversationMessageListResp\x12L\n" +
	"\x0fSendChatMessage\x12\x1b.message.SendChatMessageReq\x1a\x1c.message.SendChatMessageResp\x12K\n" +
	"\x14MarkConversationRead\x12 .message.MarkConversationReadReq\x1a\x11.message.BaseRespB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_message_proto_goTypes = []any{
	(NotificationKind)(0),               // 0: message.NotificationKind
	(SenderRole)(0),                     // 1: message.SenderRole
	(ConversationStatus)(0),             // 2: message.ConversationStatus
	(*BaseResp)(nil),                    // 3: message.BaseResp
	(*NotificationItem)(nil),            // 4: message.NotificationItem
	(*NotificationListReq)(nil),         // 5: message.NotificationListReq
	(*NotificationListResp)(nil),        // 6: message.NotificationListResp
	(*MarkNotificationReq)(nil),         // 7: message.MarkNotificationReq
	(*MarkAllNotificationsReq)(nil),     // 8: message.MarkAllNotificationsReq
	(*UnreadSummaryReq)(nil),            // 9: message.UnreadSummaryReq
	(*UnreadSummaryResp)(nil),           // 10: message.UnreadSummaryResp
	(*SendNotificationReq)(nil),         // 11: message.SendNotificationReq
	(*SendNotificationResp)(nil),        // 12: message.SendNotificationResp
	(*ConversationItem)(nil),            // 13: message.ConversationItem
	(*ConversationListReq)(nil),         // 14: message.ConversationListReq
	(*ConversationListResp)(nil),        // 15: message.ConversationListResp
	(*ChatMessageItem)(nil),             // 16: message.ChatMessageItem
	(*ConversationMessageListReq)(nil),  // 17: message.ConversationMessageListReq
	(*ConversationMessageListResp)(nil), // 18: message.ConversationMessageListResp
	(*SendChatMessageReq)(nil),          // 19: message.SendChatMessageReq
	(*SendChatMessageResp)(nil),         // 20: message.SendChatMessageResp
	(*MarkConversationReadReq)(nil),     // 21: message.MarkConversationReadReq
	nil,                                 // 22: message.NotificationItem.ExtraEntry
	nil,                                 // 23: message.SendNotificationReq.ExtraEntry
}
var file_proto_message_proto_depIdxs = []int32{
	1,  // 0: message.NotificationItem.sender_role:type_name -> message.SenderRole
	0,  // 1: message.NotificationItem.kind:type_name -> message.NotificationKind
	22, // 2: message.NotificationItem.extra:type_name -> message.NotificationItem.ExtraEntry
	4,  // 3: message.NotificationListResp.items:type_name -> message.NotificationItem
	1,  // 4: message.SendNotificationReq.sender_role:type_name -> message.SenderRole
	0,  // 5: message.SendNotificationReq.kind:type_name -> message.NotificationKind
	23, // 6: message.SendNotificationReq.extra:type_name -> message.SendNotificationReq.ExtraEntry
	1,  // 7: message.ConversationItem.peer_role:type_name -> message.SenderRole
	2,  // 8: message.ConversationItem.status:type_name -> message.ConversationStatus
	1,  // 9: message.ConversationListReq.operator_role:type_name -> message.SenderRole
	13, // 10: message.ConversationListResp.items:type_name -> message.ConversationItem
	1,  // 11: message.ChatMessageItem.sender_role:type_name -> message.SenderRole
	1,  // 12: message.ChatMessageItem.recipient_role:type_name -> message.SenderRole
	1,  // 13: message.ConversationMessageListReq.operator_role:type_name -> message.SenderRole
	16, // 14: message.ConversationMessageListResp.items:type_name -> message.ChatMessageItem
	2,  // 15: message.ConversationMessageListResp.status:type_name -> message.ConversationStatus
	1,  // 16: message.ConversationMessageListResp.pending_sender_role:type_name -> message.SenderRole
	1,  // 17: message.SendChatMessageReq.sender_role:type_name -> message.SenderRole
	1,  // 18: message.SendChatMessageReq.recipient_role:type_name -> message.SenderRole
	16, // 19: message.SendChatMessageResp.message:type_name -> message.ChatMessageItem
	2,  // 20: message.SendChatMessageResp.status:type_name -> message.ConversationStatus
	1,  // 21: message.MarkConversationReadReq.operator_role:type_name -> message.SenderRole
	11, // 22: message.MessageService.SendNotification:input_type -> message.SendNotificationReq
	5,  // 23: message.MessageService.ListNotifications:input_type -> message.NotificationListReq
	7,  // 24: message.MessageService.MarkNotificationRead:input_type -> message.MarkNotificationReq
	8,  // 25: message.MessageService.MarkAllNotificationsRead:input_type -> message.MarkAllNotificationsReq
	9,  // 26: message.MessageService.GetUnreadSummary:input_type -> message.UnreadSummaryReq
	14, // 27: message.MessageService.ListConversations:input_type -> message.ConversationListReq
	17, // 28: message.MessageService.GetConversationMessages:input_type -> message.ConversationMessageListReq
	19, // 29: message.MessageService.SendChatMessage:input_type -> message.SendChatMessageReq
	21, // 30: message.MessageService.MarkConversationRead:input_type -> message.MarkConversationReadReq
	12, // 31: message.MessageService.SendNotification:output_type -> message.SendNotificationResp
	6,  // 32: message.MessageService.ListNotifications:output_type -> message.NotificationListResp
	3,  // 33: message.MessageService.MarkNotificationRead:output_type -> message.BaseResp
	3,  // 34: message.MessageService.MarkAllNotificationsRead:output_type -> message.BaseResp
	10, // 35: message.MessageService.GetUnreadSummary:output_type -> message.UnreadSummaryResp
	15, // 36: message.MessageService.ListConversations:output_type -> message.ConversationListResp
	18, // 37: message.MessageService.GetConversationMessages:output_type -> message.ConversationMessageListResp
	20, // 38: message.MessageService.SendChatMessage:output_type -> message.SendChatMessageResp
	3,  // 39: message.MessageService.MarkConversationRead:output_type -> message.BaseResp
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		EnumInfos:         file_proto_message_proto_enumTypes,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
