// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/message.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageService_SendNotification_FullMethodName         = "/message.MessageService/SendNotification"
	MessageService_ListNotifications_FullMethodName        = "/message.MessageService/ListNotifications"
	MessageService_MarkNotificationRead_FullMethodName     = "/message.MessageService/MarkNotificationRead"
	MessageService_MarkAllNotificationsRead_FullMethodName = "/message.MessageService/MarkAllNotificationsRead"
	MessageService_GetUnreadSummary_FullMethodName         = "/message.MessageService/GetUnreadSummary"
	MessageService_ListConversations_FullMethodName        = "/message.MessageService/ListConversations"
	MessageService_GetConversationMessages_FullMethodName  = "/message.MessageService/GetConversationMessages"
	MessageService_SendChatMessage_FullMethodName          = "/message.MessageService/SendChatMessage"
	MessageService_MarkConversationRead_FullMethodName     = "/message.MessageService/MarkConversationRead"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error)
	ListNotifications(ctx context.Context, in *NotificationListReq, opts ...grpc.CallOption) (*NotificationListResp, error)
	MarkNotificationRead(ctx context.Context, in *MarkNotificationReq, opts ...grpc.CallOption) (*BaseResp, error)
	MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReq, opts ...grpc.CallOption) (*BaseResp, error)
	GetUnreadSummary(ctx context.Context, in *UnreadSummaryReq, opts ...grpc.CallOption) (*UnreadSummaryResp, error)
	ListConversations(ctx context.Context, in *ConversationListReq, opts ...grpc.CallOption) (*ConversationListResp, error)
	GetConversationMessages(ctx context.Context, in *ConversationMessageListReq, opts ...grpc.CallOption) (*ConversationMessageListResp, error)
	SendChatMessage(ctx context.Context, in *SendChatMessageReq, opts ...grpc.CallOption) (*SendChatMessageResp, error)
	MarkConversationRead(ctx context.Context, in *MarkConversationReadReq, opts ...grpc.CallOption) (*BaseResp, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResp)
	err := c.cc.Invoke(ctx, MessageService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ListNotifications(ctx context.Context, in *NotificationListReq, opts ...grpc.CallOption) (*NotificationListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationListResp)
	err := c.cc.Invoke(ctx, MessageService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MarkNotificationRead(ctx context.Context, in *MarkNotificationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MessageService_MarkNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MessageService_MarkAllNotificationsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetUnreadSummary(ctx context.Context, in *UnreadSummaryReq, opts ...grpc.CallOption) (*UnreadSummaryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnreadSummaryResp)
	err := c.cc.Invoke(ctx, MessageService_GetUnreadSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ListConversations(ctx context.Context, in *ConversationListReq, opts ...grpc.CallOption) (*ConversationListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationListResp)
	err := c.cc.Invoke(ctx, MessageService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetConversationMessages(ctx context.Context, in *ConversationMessageListReq, opts ...grpc.CallOption) (*ConversationMessageListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationMessageListResp)
	err := c.cc.Invoke(ctx, MessageService_GetConversationMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SendChatMessage(ctx context.Context, in *SendChatMessageReq, opts ...grpc.CallOption) (*SendChatMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatMessageResp)
	err := c.cc.Invoke(ctx, MessageService_SendChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MarkConversationRead(ctx context.Context, in *MarkConversationReadReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MessageService_MarkConversationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility.
type MessageServiceServer interface {
	SendNotification(context.Context, *SendNotificationReq) (*SendNotificationResp, error)
	ListNotifications(context.Context, *NotificationListReq) (*NotificationListResp, error)
	MarkNotificationRead(context.Context, *MarkNotificationReq) (*BaseResp, error)
	MarkAllNotificationsRead(context.Context, *MarkAllNotificationsReq) (*BaseResp, error)
	GetUnreadSummary(context.Context, *UnreadSummaryReq) (*UnreadSummaryResp, error)
	ListConversations(context.Context, *ConversationListReq) (*ConversationListResp, error)
	GetConversationMessages(context.Context, *ConversationMessageListReq) (*ConversationMessageListResp, error)
	SendChatMessage(context.Context, *SendChatMessageReq) (*SendChatMessageResp, error)
	MarkConversationRead(context.Context, *MarkConversationReadReq) (*BaseResp, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceServer struct{}

func (UnimplementedMessageServiceServer) SendNotification(context.Context, *SendNotificationReq) (*SendNotificationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedMessageServiceServer) ListNotifications(context.Context, *NotificationListReq) (*NotificationListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedMessageServiceServer) MarkNotificationRead(context.Context, *MarkNotificationReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationRead not implemented")
}
func (UnimplementedMessageServiceServer) MarkAllNotificationsRead(context.Context, *MarkAllNotificationsReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllNotificationsRead not implemented")
}
func (UnimplementedMessageServiceServer) GetUnreadSummary(context.Context, *UnreadSummaryReq) (*UnreadSummaryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadSummary not implemented")
}
func (UnimplementedMessageServiceServer) ListConversations(context.Context, *ConversationListReq) (*ConversationListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedMessageServiceServer) GetConversationMessages(context.Context, *ConversationMessageListReq) (*ConversationMessageListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversationMessages not implemented")
}
func (UnimplementedMessageServiceServer) SendChatMessage(context.Context, *SendChatMessageReq) (*SendChatMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendChatMessage not implemented")
}
func (UnimplementedMessageServiceServer) MarkConversationRead(context.Context, *MarkConversationReadReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkConversationRead not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}
func (UnimplementedMessageServiceServer) testEmbeddedByValue()                        {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	// If the following call panics, it indicates UnimplementedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendNotification(ctx, req.(*SendNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ListNotifications(ctx, req.(*NotificationListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MarkNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MarkNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MarkNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MarkNotificationRead(ctx, req.(*MarkNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MarkAllNotificationsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllNotificationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MarkAllNotificationsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MarkAllNotificationsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MarkAllNotificationsRead(ctx, req.(*MarkAllNotificationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetUnreadSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnreadSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetUnreadSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_GetUnreadSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetUnreadSummary(ctx, req.(*UnreadSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ListConversations(ctx, req.(*ConversationListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetConversationMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationMessageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetConversationMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_GetConversationMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetConversationMessages(ctx, req.(*ConversationMessageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SendChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChatMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_SendChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendChatMessage(ctx, req.(*SendChatMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MarkConversationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkConversationReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MarkConversationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MarkConversationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MarkConversationRead(ctx, req.(*MarkConversationReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _MessageService_SendNotification_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _MessageService_ListNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationRead",
			Handler:    _MessageService_MarkNotificationRead_Handler,
		},
		{
			MethodName: "MarkAllNotificationsRead",
			Handler:    _MessageService_MarkAllNotificationsRead_Handler,
		},
		{
			MethodName: "GetUnreadSummary",
			Handler:    _MessageService_GetUnreadSummary_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _MessageService_ListConversations_Handler,
		},
		{
			MethodName: "GetConversationMessages",
			Handler:    _MessageService_GetConversationMessages_Handler,
		},
		{
			MethodName: "SendChatMessage",
			Handler:    _MessageService_SendChatMessage_Handler,
		},
		{
			MethodName: "MarkConversationRead",
			Handler:    _MessageService_MarkConversationRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message.proto",
}
