// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: security.proto

package server

import (
	"context"

	imagesecurityservicelogic "sea-try-go/service/security/rpc/internal/logic/imagesecurityservice"
	"sea-try-go/service/security/rpc/internal/svc"
	"sea-try-go/service/security/rpc/pb/sea-try-go/service/security/rpc/pb"
)

type ImageSecurityServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImageSecurityServiceServer
}

func NewImageSecurityServiceServer(svcCtx *svc.ServiceContext) *ImageSecurityServiceServer {
	return &ImageSecurityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ImageSecurityServiceServer) DetectImageAd(ctx context.Context, in *pb.DetectImageAdRequest) (*pb.DetectImageAdResponse, error) {
	l := imagesecurityservicelogic.NewDetectImageAdLogic(ctx, s.svcCtx)
	return l.DetectImageAd(in)
}

func (s *ImageSecurityServiceServer) DetectImageAdBatch(ctx context.Context, in *pb.DetectImageAdBatchRequest) (*pb.DetectImageAdBatchResponse, error) {
	l := imagesecurityservicelogic.NewDetectImageAdBatchLogic(ctx, s.svcCtx)
	return l.DetectImageAdBatch(in)
}
