// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package server

import (
	"context"

	"sea-try-go/service/message/rpc/internal/logic"
	"sea-try-go/service/message/rpc/internal/svc"
	"sea-try-go/service/message/rpc/pb"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) SendNotification(ctx context.Context, in *pb.SendNotificationReq) (*pb.SendNotificationResp, error) {
	l := logic.NewSendNotificationLogic(ctx, s.svcCtx)
	return l.SendNotification(in)
}

func (s *MessageServiceServer) ListNotifications(ctx context.Context, in *pb.NotificationListReq) (*pb.NotificationListResp, error) {
	l := logic.NewListNotificationsLogic(ctx, s.svcCtx)
	return l.ListNotifications(in)
}

func (s *MessageServiceServer) MarkNotificationRead(ctx context.Context, in *pb.MarkNotificationReq) (*pb.BaseResp, error) {
	l := logic.NewMarkNotificationReadLogic(ctx, s.svcCtx)
	return l.MarkNotificationRead(in)
}

func (s *MessageServiceServer) MarkAllNotificationsRead(ctx context.Context, in *pb.MarkAllNotificationsReq) (*pb.BaseResp, error) {
	l := logic.NewMarkAllNotificationsReadLogic(ctx, s.svcCtx)
	return l.MarkAllNotificationsRead(in)
}

func (s *MessageServiceServer) GetUnreadSummary(ctx context.Context, in *pb.UnreadSummaryReq) (*pb.UnreadSummaryResp, error) {
	l := logic.NewGetUnreadSummaryLogic(ctx, s.svcCtx)
	return l.GetUnreadSummary(in)
}

func (s *MessageServiceServer) ListConversations(ctx context.Context, in *pb.ConversationListReq) (*pb.ConversationListResp, error) {
	l := logic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

func (s *MessageServiceServer) GetConversationMessages(ctx context.Context, in *pb.ConversationMessageListReq) (*pb.ConversationMessageListResp, error) {
	l := logic.NewGetConversationMessagesLogic(ctx, s.svcCtx)
	return l.GetConversationMessages(in)
}

func (s *MessageServiceServer) SendChatMessage(ctx context.Context, in *pb.SendChatMessageReq) (*pb.SendChatMessageResp, error) {
	l := logic.NewSendChatMessageLogic(ctx, s.svcCtx)
	return l.SendChatMessage(in)
}

func (s *MessageServiceServer) MarkConversationRead(ctx context.Context, in *pb.MarkConversationReadReq) (*pb.BaseResp, error) {
	l := logic.NewMarkConversationReadLogic(ctx, s.svcCtx)
	return l.MarkConversationRead(in)
}
