// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Article struct {
	Id            string            `json:"id"`
	Title         string            `json:"title"`
	Brief         string            `json:"brief"`
	Content       string            `json:"content"`
	CoverImageUrl string            `json:"cover_image_url"`
	ManualTypeTag string            `json:"manual_type_tag"`
	SecondaryTags []string          `json:"secondary_tags"`
	AuthorId      string            `json:"author_id"`
	AuthorName    string            `json:"author_name"`
	CreateTime    int64             `json:"create_time"`
	UpdateTime    int64             `json:"update_time"`
	Status        int32             `json:"status"`
	ViewCount     int32             `json:"view_count"`
	LikeCount     int32             `json:"like_count"`
	CommentCount  int32             `json:"comment_count"`
	ShareCount    int32             `json:"share_count"`
	ExtInfo       map[string]string `json:"ext_info"`
}

type CreateArticleReq struct {
	Title         string   `json:"title"`
	Brief         string   `json:"brief,optional"`
	ContentPath   string   `json:"content_path"`
	CoverImageUrl string   `json:"cover_image_url,optional"`
	ManualTypeTag string   `json:"manual_type_tag,optional"`
	SecondaryTags []string `json:"secondary_tags,optional"`
}

type CreateArticleResp struct {
	ArticleId string `json:"article_id"`
}

type DeleteArticleReq struct {
	ArticleId string `path:"id"`
}

type DeleteArticleResp struct {
	Success bool `json:"success"`
}

type GetArticleReq struct {
	ArticleId string `path:"id"`
	IncrView  bool   `form:"incr_view,optional"`
}

type GetArticleResp struct {
	Article Article `json:"article"`
}

type GetPresignedUploadUrlReq struct {
	FileName    string `form:"file_name"`
	ContentType string `form:"content_type"`
}

type GetPresignedUploadUrlResp struct {
	UploadUrl  string `json:"upload_url"`
	ObjectName string `json:"object_name"`
}

type ListArticlesReq struct {
	ManualTypeTag string `form:"manual_type_tag,optional"`
	SecondaryTag  string `form:"secondary_tag,optional"`
	RelatedGameId string `form:"related_game_id,optional"`
	AuthorId      string `form:"author_id,optional"`
	Page          int32  `form:"page,default=1"`
	PageSize      int32  `form:"page_size,default=20"`
	SortBy        string `form:"sort_by,default=create_time"`
	Desc          bool   `form:"desc,default=true"`
}

type ListArticlesResp struct {
	Articles []Article `json:"articles"`
	Total    int64     `json:"total"`
	Page     int32     `json:"page"`
	PageSize int32     `json:"page_size"`
}

type UpdateArticleReq struct {
	ArticleId     string   `path:"id"`
	Title         string   `json:"title,optional"`
	Brief         string   `json:"brief,optional"`
	ContentPath   string   `json:"content_path,optional"`
	CoverImageUrl string   `json:"cover_image_url,optional"`
	ManualTypeTag string   `json:"manual_type_tag,optional"`
	SecondaryTags []string `json:"secondary_tags,optional"`
	Status        int32    `json:"status,optional"`
}

type UpdateArticleResp struct {
	Success bool `json:"success"`
}

type UploadImageReq struct {
}

type UploadImageResp struct {
	ImageUrl string `json:"image_url"`
}
